# Don't edit the `bin` list manually! It is updated by `cargo dev update`. This comment line will be stripped in `rustlings init`.
bin = [
  { name = "intro1", path = "../exercises/00_intro/intro1.rs" },
  { name = "intro1_sol", path = "../solutions/00_intro/intro1.rs" },
  { name = "intro2", path = "../exercises/00_intro/intro2.rs" },
  { name = "intro2_sol", path = "../solutions/00_intro/intro2.rs" },
  { name = "variables1", path = "../exercises/01_variables/variables1.rs" },
  { name = "variables1_sol", path = "../solutions/01_variables/variables1.rs" },
  { name = "variables2", path = "../exercises/01_variables/variables2.rs" },
  { name = "variables2_sol", path = "../solutions/01_variables/variables2.rs" },
  { name = "variables3", path = "../exercises/01_variables/variables3.rs" },
  { name = "variables3_sol", path = "../solutions/01_variables/variables3.rs" },
  { name = "variables4", path = "../exercises/01_variables/variables4.rs" },
  { name = "variables4_sol", path = "../solutions/01_variables/variables4.rs" },
  { name = "variables5", path = "../exercises/01_variables/variables5.rs" },
  { name = "variables5_sol", path = "../solutions/01_variables/variables5.rs" },
  { name = "variables6", path = "../exercises/01_variables/variables6.rs" },
  { name = "variables6_sol", path = "../solutions/01_variables/variables6.rs" },
  { name = "functions1", path = "../exercises/02_functions/functions1.rs" },
  { name = "functions1_sol", path = "../solutions/02_functions/functions1.rs" },
  { name = "functions2", path = "../exercises/02_functions/functions2.rs" },
  { name = "functions2_sol", path = "../solutions/02_functions/functions2.rs" },
  { name = "functions3", path = "../exercises/02_functions/functions3.rs" },
  { name = "functions3_sol", path = "../solutions/02_functions/functions3.rs" },
  { name = "functions4", path = "../exercises/02_functions/functions4.rs" },
  { name = "functions4_sol", path = "../solutions/02_functions/functions4.rs" },
  { name = "functions5", path = "../exercises/02_functions/functions5.rs" },
  { name = "functions5_sol", path = "../solutions/02_functions/functions5.rs" },
  { name = "if1", path = "../exercises/03_if/if1.rs" },
  { name = "if1_sol", path = "../solutions/03_if/if1.rs" },
  { name = "if2", path = "../exercises/03_if/if2.rs" },
  { name = "if2_sol", path = "../solutions/03_if/if2.rs" },
  { name = "if3", path = "../exercises/03_if/if3.rs" },
  { name = "if3_sol", path = "../solutions/03_if/if3.rs" },
  { name = "quiz1", path = "../exercises/quizzes/quiz1.rs" },
  { name = "quiz1_sol", path = "../solutions/quizzes/quiz1.rs" },
  { name = "primitive_types1", path = "../exercises/04_primitive_types/primitive_types1.rs" },
  { name = "primitive_types1_sol", path = "../solutions/04_primitive_types/primitive_types1.rs" },
  { name = "primitive_types2", path = "../exercises/04_primitive_types/primitive_types2.rs" },
  { name = "primitive_types2_sol", path = "../solutions/04_primitive_types/primitive_types2.rs" },
  { name = "primitive_types3", path = "../exercises/04_primitive_types/primitive_types3.rs" },
  { name = "primitive_types3_sol", path = "../solutions/04_primitive_types/primitive_types3.rs" },
  { name = "primitive_types4", path = "../exercises/04_primitive_types/primitive_types4.rs" },
  { name = "primitive_types4_sol", path = "../solutions/04_primitive_types/primitive_types4.rs" },
  { name = "primitive_types5", path = "../exercises/04_primitive_types/primitive_types5.rs" },
  { name = "primitive_types5_sol", path = "../solutions/04_primitive_types/primitive_types5.rs" },
  { name = "primitive_types6", path = "../exercises/04_primitive_types/primitive_types6.rs" },
  { name = "primitive_types6_sol", path = "../solutions/04_primitive_types/primitive_types6.rs" },
  { name = "vecs1", path = "../exercises/05_vecs/vecs1.rs" },
  { name = "vecs1_sol", path = "../solutions/05_vecs/vecs1.rs" },
  { name = "vecs2", path = "../exercises/05_vecs/vecs2.rs" },
  { name = "vecs2_sol", path = "../solutions/05_vecs/vecs2.rs" },
  { name = "move_semantics1", path = "../exercises/06_move_semantics/move_semantics1.rs" },
  { name = "move_semantics1_sol", path = "../solutions/06_move_semantics/move_semantics1.rs" },
  { name = "move_semantics2", path = "../exercises/06_move_semantics/move_semantics2.rs" },
  { name = "move_semantics2_sol", path = "../solutions/06_move_semantics/move_semantics2.rs" },
  { name = "move_semantics3", path = "../exercises/06_move_semantics/move_semantics3.rs" },
  { name = "move_semantics3_sol", path = "../solutions/06_move_semantics/move_semantics3.rs" },
  { name = "move_semantics4", path = "../exercises/06_move_semantics/move_semantics4.rs" },
  { name = "move_semantics4_sol", path = "../solutions/06_move_semantics/move_semantics4.rs" },
  { name = "move_semantics5", path = "../exercises/06_move_semantics/move_semantics5.rs" },
  { name = "move_semantics5_sol", path = "../solutions/06_move_semantics/move_semantics5.rs" },
  { name = "structs1", path = "../exercises/07_structs/structs1.rs" },
  { name = "structs1_sol", path = "../solutions/07_structs/structs1.rs" },
  { name = "structs2", path = "../exercises/07_structs/structs2.rs" },
  { name = "structs2_sol", path = "../solutions/07_structs/structs2.rs" },
  { name = "structs3", path = "../exercises/07_structs/structs3.rs" },
  { name = "structs3_sol", path = "../solutions/07_structs/structs3.rs" },
  { name = "enums1", path = "../exercises/08_enums/enums1.rs" },
  { name = "enums1_sol", path = "../solutions/08_enums/enums1.rs" },
  { name = "enums2", path = "../exercises/08_enums/enums2.rs" },
  { name = "enums2_sol", path = "../solutions/08_enums/enums2.rs" },
  { name = "enums3", path = "../exercises/08_enums/enums3.rs" },
  { name = "enums3_sol", path = "../solutions/08_enums/enums3.rs" },
  { name = "strings1", path = "../exercises/09_strings/strings1.rs" },
  { name = "strings1_sol", path = "../solutions/09_strings/strings1.rs" },
  { name = "strings2", path = "../exercises/09_strings/strings2.rs" },
  { name = "strings2_sol", path = "../solutions/09_strings/strings2.rs" },
  { name = "strings3", path = "../exercises/09_strings/strings3.rs" },
  { name = "strings3_sol", path = "../solutions/09_strings/strings3.rs" },
  { name = "strings4", path = "../exercises/09_strings/strings4.rs" },
  { name = "strings4_sol", path = "../solutions/09_strings/strings4.rs" },
  { name = "modules1", path = "../exercises/10_modules/modules1.rs" },
  { name = "modules1_sol", path = "../solutions/10_modules/modules1.rs" },
  { name = "modules2", path = "../exercises/10_modules/modules2.rs" },
  { name = "modules2_sol", path = "../solutions/10_modules/modules2.rs" },
  { name = "modules3", path = "../exercises/10_modules/modules3.rs" },
  { name = "modules3_sol", path = "../solutions/10_modules/modules3.rs" },
  { name = "hashmaps1", path = "../exercises/11_hashmaps/hashmaps1.rs" },
  { name = "hashmaps1_sol", path = "../solutions/11_hashmaps/hashmaps1.rs" },
  { name = "hashmaps2", path = "../exercises/11_hashmaps/hashmaps2.rs" },
  { name = "hashmaps2_sol", path = "../solutions/11_hashmaps/hashmaps2.rs" },
  { name = "hashmaps3", path = "../exercises/11_hashmaps/hashmaps3.rs" },
  { name = "hashmaps3_sol", path = "../solutions/11_hashmaps/hashmaps3.rs" },
  { name = "quiz2", path = "../exercises/quizzes/quiz2.rs" },
  { name = "quiz2_sol", path = "../solutions/quizzes/quiz2.rs" },
  { name = "options1", path = "../exercises/12_options/options1.rs" },
  { name = "options1_sol", path = "../solutions/12_options/options1.rs" },
  { name = "options2", path = "../exercises/12_options/options2.rs" },
  { name = "options2_sol", path = "../solutions/12_options/options2.rs" },
  { name = "options3", path = "../exercises/12_options/options3.rs" },
  { name = "options3_sol", path = "../solutions/12_options/options3.rs" },
  { name = "errors1", path = "../exercises/13_error_handling/errors1.rs" },
  { name = "errors1_sol", path = "../solutions/13_error_handling/errors1.rs" },
  { name = "errors2", path = "../exercises/13_error_handling/errors2.rs" },
  { name = "errors2_sol", path = "../solutions/13_error_handling/errors2.rs" },
  { name = "errors3", path = "../exercises/13_error_handling/errors3.rs" },
  { name = "errors3_sol", path = "../solutions/13_error_handling/errors3.rs" },
  { name = "errors4", path = "../exercises/13_error_handling/errors4.rs" },
  { name = "errors4_sol", path = "../solutions/13_error_handling/errors4.rs" },
  { name = "errors5", path = "../exercises/13_error_handling/errors5.rs" },
  { name = "errors5_sol", path = "../solutions/13_error_handling/errors5.rs" },
  { name = "errors6", path = "../exercises/13_error_handling/errors6.rs" },
  { name = "errors6_sol", path = "../solutions/13_error_handling/errors6.rs" },
  { name = "generics1", path = "../exercises/14_generics/generics1.rs" },
  { name = "generics1_sol", path = "../solutions/14_generics/generics1.rs" },
  { name = "generics2", path = "../exercises/14_generics/generics2.rs" },
  { name = "generics2_sol", path = "../solutions/14_generics/generics2.rs" },
  { name = "traits1", path = "../exercises/15_traits/traits1.rs" },
  { name = "traits1_sol", path = "../solutions/15_traits/traits1.rs" },
  { name = "traits2", path = "../exercises/15_traits/traits2.rs" },
  { name = "traits2_sol", path = "../solutions/15_traits/traits2.rs" },
  { name = "traits3", path = "../exercises/15_traits/traits3.rs" },
  { name = "traits3_sol", path = "../solutions/15_traits/traits3.rs" },
  { name = "traits4", path = "../exercises/15_traits/traits4.rs" },
  { name = "traits4_sol", path = "../solutions/15_traits/traits4.rs" },
  { name = "traits5", path = "../exercises/15_traits/traits5.rs" },
  { name = "traits5_sol", path = "../solutions/15_traits/traits5.rs" },
  { name = "quiz3", path = "../exercises/quizzes/quiz3.rs" },
  { name = "quiz3_sol", path = "../solutions/quizzes/quiz3.rs" },
  { name = "lifetimes1", path = "../exercises/16_lifetimes/lifetimes1.rs" },
  { name = "lifetimes1_sol", path = "../solutions/16_lifetimes/lifetimes1.rs" },
  { name = "lifetimes2", path = "../exercises/16_lifetimes/lifetimes2.rs" },
  { name = "lifetimes2_sol", path = "../solutions/16_lifetimes/lifetimes2.rs" },
  { name = "lifetimes3", path = "../exercises/16_lifetimes/lifetimes3.rs" },
  { name = "lifetimes3_sol", path = "../solutions/16_lifetimes/lifetimes3.rs" },
  { name = "tests1", path = "../exercises/17_tests/tests1.rs" },
  { name = "tests1_sol", path = "../solutions/17_tests/tests1.rs" },
  { name = "tests2", path = "../exercises/17_tests/tests2.rs" },
  { name = "tests2_sol", path = "../solutions/17_tests/tests2.rs" },
  { name = "tests3", path = "../exercises/17_tests/tests3.rs" },
  { name = "tests3_sol", path = "../solutions/17_tests/tests3.rs" },
  { name = "iterators1", path = "../exercises/18_iterators/iterators1.rs" },
  { name = "iterators1_sol", path = "../solutions/18_iterators/iterators1.rs" },
  { name = "iterators2", path = "../exercises/18_iterators/iterators2.rs" },
  { name = "iterators2_sol", path = "../solutions/18_iterators/iterators2.rs" },
  { name = "iterators3", path = "../exercises/18_iterators/iterators3.rs" },
  { name = "iterators3_sol", path = "../solutions/18_iterators/iterators3.rs" },
  { name = "iterators4", path = "../exercises/18_iterators/iterators4.rs" },
  { name = "iterators4_sol", path = "../solutions/18_iterators/iterators4.rs" },
  { name = "iterators5", path = "../exercises/18_iterators/iterators5.rs" },
  { name = "iterators5_sol", path = "../solutions/18_iterators/iterators5.rs" },
  { name = "smart_pointers1", path = "../exercises/19_smart_pointers/smart_pointers1.rs" },
  { name = "smart_pointers1_sol", path = "../solutions/19_smart_pointers/smart_pointers1.rs" },
  { name = "smart_pointers2", path = "../exercises/19_smart_pointers/smart_pointers2.rs" },
  { name = "smart_pointers2_sol", path = "../solutions/19_smart_pointers/smart_pointers2.rs" },
  { name = "smart_pointers3", path = "../exercises/19_smart_pointers/smart_pointers3.rs" },
  { name = "smart_pointers3_sol", path = "../solutions/19_smart_pointers/smart_pointers3.rs" },
  { name = "smart_pointers4", path = "../exercises/19_smart_pointers/smart_pointers4.rs" },
  { name = "smart_pointers4_sol", path = "../solutions/19_smart_pointers/smart_pointers4.rs" },
  { name = "threads1", path = "../exercises/20_threads/threads1.rs" },
  { name = "threads1_sol", path = "../solutions/20_threads/threads1.rs" },
  { name = "threads2", path = "../exercises/20_threads/threads2.rs" },
  { name = "threads2_sol", path = "../solutions/20_threads/threads2.rs" },
  { name = "threads3", path = "../exercises/20_threads/threads3.rs" },
  { name = "threads3_sol", path = "../solutions/20_threads/threads3.rs" },
  { name = "macros1", path = "../exercises/21_macros/macros1.rs" },
  { name = "macros1_sol", path = "../solutions/21_macros/macros1.rs" },
  { name = "macros2", path = "../exercises/21_macros/macros2.rs" },
  { name = "macros2_sol", path = "../solutions/21_macros/macros2.rs" },
  { name = "macros3", path = "../exercises/21_macros/macros3.rs" },
  { name = "macros3_sol", path = "../solutions/21_macros/macros3.rs" },
  { name = "macros4", path = "../exercises/21_macros/macros4.rs" },
  { name = "macros4_sol", path = "../solutions/21_macros/macros4.rs" },
  { name = "clippy1", path = "../exercises/22_clippy/clippy1.rs" },
  { name = "clippy1_sol", path = "../solutions/22_clippy/clippy1.rs" },
  { name = "clippy2", path = "../exercises/22_clippy/clippy2.rs" },
  { name = "clippy2_sol", path = "../solutions/22_clippy/clippy2.rs" },
  { name = "clippy3", path = "../exercises/22_clippy/clippy3.rs" },
  { name = "clippy3_sol", path = "../solutions/22_clippy/clippy3.rs" },
  { name = "conversions1", path = "../exercises/23_conversions/conversions1.rs" },
  { name = "conversions1_sol", path = "../solutions/23_conversions/conversions1.rs" },
  { name = "conversions2", path = "../exercises/23_conversions/conversions2.rs" },
  { name = "conversions2_sol", path = "../solutions/23_conversions/conversions2.rs" },
  { name = "conversions3", path = "../exercises/23_conversions/conversions3.rs" },
  { name = "conversions3_sol", path = "../solutions/23_conversions/conversions3.rs" },
  { name = "conversions4", path = "../exercises/23_conversions/conversions4.rs" },
  { name = "conversions4_sol", path = "../solutions/23_conversions/conversions4.rs" },
  { name = "conversions5", path = "../exercises/23_conversions/conversions5.rs" },
  { name = "conversions5_sol", path = "../solutions/23_conversions/conversions5.rs" },
  { name = "ownership1", path = "../exercises/24_ownership_model/ownership1.rs" },
  { name = "ownership1_sol", path = "../solutions/24_ownership_model/ownership1.rs" },
  { name = "ownership2", path = "../exercises/24_ownership_model/ownership2.rs" },
  { name = "ownership2_sol", path = "../solutions/24_ownership_model/ownership2.rs" },
  { name = "ownership3", path = "../exercises/24_ownership_model/ownership3.rs" },
  { name = "ownership3_sol", path = "../solutions/24_ownership_model/ownership3.rs" },
  { name = "ownership4", path = "../exercises/24_ownership_model/ownership4.rs" },
  { name = "ownership4_sol", path = "../solutions/24_ownership_model/ownership4.rs" },
  { name = "ownership5", path = "../exercises/24_ownership_model/ownership5.rs" },
  { name = "ownership5_sol", path = "../solutions/24_ownership_model/ownership5.rs" },
  { name = "ownership6", path = "../exercises/24_ownership_model/ownership6.rs" },
  { name = "ownership6_sol", path = "../solutions/24_ownership_model/ownership6.rs" },
  { name = "lifetimes4", path = "../exercises/25_lifetimes_deep/lifetimes4.rs" },
  { name = "lifetimes4_sol", path = "../solutions/25_lifetimes_deep/lifetimes4.rs" },
  { name = "lifetimes5", path = "../exercises/25_lifetimes_deep/lifetimes5.rs" },
  { name = "lifetimes5_sol", path = "../solutions/25_lifetimes_deep/lifetimes5.rs" },
  { name = "lifetimes6", path = "../exercises/25_lifetimes_deep/lifetimes6.rs" },
  { name = "lifetimes6_sol", path = "../solutions/25_lifetimes_deep/lifetimes6.rs" },
  { name = "lifetimes7", path = "../exercises/25_lifetimes_deep/lifetimes7.rs" },
  { name = "lifetimes7_sol", path = "../solutions/25_lifetimes_deep/lifetimes7.rs" },
  { name = "lifetimes8", path = "../exercises/25_lifetimes_deep/lifetimes8.rs" },
  { name = "lifetimes8_sol", path = "../solutions/25_lifetimes_deep/lifetimes8.rs" },
  { name = "lifetimes9", path = "../exercises/25_lifetimes_deep/lifetimes9.rs" },
  { name = "lifetimes9_sol", path = "../solutions/25_lifetimes_deep/lifetimes9.rs" },
  { name = "borrowck1", path = "../exercises/37_borrowck_errors/borrowck1.rs" },
  { name = "borrowck1_sol", path = "../solutions/37_borrowck_errors/borrowck1.rs" },
  { name = "borrowck2", path = "../exercises/37_borrowck_errors/borrowck2.rs" },
  { name = "borrowck2_sol", path = "../solutions/37_borrowck_errors/borrowck2.rs" },
  { name = "borrowck3", path = "../exercises/37_borrowck_errors/borrowck3.rs" },
  { name = "borrowck3_sol", path = "../solutions/37_borrowck_errors/borrowck3.rs" },
  { name = "borrowck4", path = "../exercises/37_borrowck_errors/borrowck4.rs" },
  { name = "borrowck4_sol", path = "../solutions/37_borrowck_errors/borrowck4.rs" },
  { name = "smartptr1", path = "../exercises/26_smart_pointers_deep/smartptr1.rs" },
  { name = "smartptr1_sol", path = "../solutions/26_smart_pointers_deep/smartptr1.rs" },
  { name = "smartptr2", path = "../exercises/26_smart_pointers_deep/smartptr2.rs" },
  { name = "smartptr2_sol", path = "../solutions/26_smart_pointers_deep/smartptr2.rs" },
  { name = "smartptr3", path = "../exercises/26_smart_pointers_deep/smartptr3.rs" },
  { name = "smartptr3_sol", path = "../solutions/26_smart_pointers_deep/smartptr3.rs" },
  { name = "drop1", path = "../exercises/39_drop_raii/drop1.rs" },
  { name = "drop1_sol", path = "../solutions/39_drop_raii/drop1.rs" },
  { name = "drop2", path = "../exercises/39_drop_raii/drop2.rs" },
  { name = "drop2_sol", path = "../solutions/39_drop_raii/drop2.rs" },
  { name = "raii1", path = "../exercises/39_drop_raii/raii1.rs" },
  { name = "raii1_sol", path = "../solutions/39_drop_raii/raii1.rs" },
  { name = "raii2", path = "../exercises/39_drop_raii/raii2.rs" },
  { name = "raii2_sol", path = "../solutions/39_drop_raii/raii2.rs" },
  { name = "raii3", path = "../exercises/39_drop_raii/raii3.rs" },
  { name = "raii3_sol", path = "../solutions/39_drop_raii/raii3.rs" },
  { name = "raii4", path = "../exercises/39_drop_raii/raii4.rs" },
  { name = "raii4_sol", path = "../solutions/39_drop_raii/raii4.rs" },
  { name = "cell1", path = "../exercises/40_interior_mutability/cell1.rs" },
  { name = "cell1_sol", path = "../solutions/40_interior_mutability/cell1.rs" },
  { name = "cell2", path = "../exercises/40_interior_mutability/cell2.rs" },
  { name = "cell2_sol", path = "../solutions/40_interior_mutability/cell2.rs" },
  { name = "cell3", path = "../exercises/40_interior_mutability/cell3.rs" },
  { name = "cell3_sol", path = "../solutions/40_interior_mutability/cell3.rs" },
  { name = "cell4", path = "../exercises/40_interior_mutability/cell4.rs" },
  { name = "cell4_sol", path = "../solutions/40_interior_mutability/cell4.rs" },
  { name = "layout1", path = "../exercises/41_memory_layout/layout1.rs" },
  { name = "layout1_sol", path = "../solutions/41_memory_layout/layout1.rs" },
  { name = "layout2", path = "../exercises/41_memory_layout/layout2.rs" },
  { name = "layout2_sol", path = "../solutions/41_memory_layout/layout2.rs" },
  { name = "dispatch1", path = "../exercises/32_dispatch/dispatch1.rs" },
  { name = "dispatch1_sol", path = "../solutions/32_dispatch/dispatch1.rs" },
  { name = "dispatch2", path = "../exercises/32_dispatch/dispatch2.rs" },
  { name = "dispatch2_sol", path = "../solutions/32_dispatch/dispatch2.rs" },
  { name = "dispatch3", path = "../exercises/32_dispatch/dispatch3.rs" },
  { name = "dispatch3_sol", path = "../solutions/32_dispatch/dispatch3.rs" },
  { name = "dispatch4", path = "../exercises/32_dispatch/dispatch4.rs" },
  { name = "dispatch4_sol", path = "../solutions/32_dispatch/dispatch4.rs" },
  { name = "dispatch5", path = "../exercises/32_dispatch/dispatch5.rs" },
  { name = "dispatch5_sol", path = "../solutions/32_dispatch/dispatch5.rs" },
  { name = "dispatch6", path = "../exercises/32_dispatch/dispatch6.rs" },
  { name = "dispatch6_sol", path = "../solutions/32_dispatch/dispatch6.rs" },
  { name = "closure1", path = "../exercises/33_closures/closure1.rs" },
  { name = "closure1_sol", path = "../solutions/33_closures/closure1.rs" },
  { name = "closure2", path = "../exercises/33_closures/closure2.rs" },
  { name = "closure2_sol", path = "../solutions/33_closures/closure2.rs" },
  { name = "closure3", path = "../exercises/33_closures/closure3.rs" },
  { name = "closure3_sol", path = "../solutions/33_closures/closure3.rs" },
  { name = "closure4", path = "../exercises/33_closures/closure4.rs" },
  { name = "closure4_sol", path = "../solutions/33_closures/closure4.rs" },
  { name = "closure5", path = "../exercises/33_closures/closure5.rs" },
  { name = "closure5_sol", path = "../solutions/33_closures/closure5.rs" },
  { name = "closure6", path = "../exercises/33_closures/closure6.rs" },
  { name = "closure6_sol", path = "../solutions/33_closures/closure6.rs" },
  { name = "closure7", path = "../exercises/33_closures/closure7.rs" },
  { name = "closure7_sol", path = "../solutions/33_closures/closure7.rs" },
  { name = "closure8", path = "../exercises/33_closures/closure8.rs" },
  { name = "closure8_sol", path = "../solutions/33_closures/closure8.rs" },
  { name = "iter1", path = "../exercises/34_iterators/iter1.rs" },
  { name = "iter1_sol", path = "../solutions/34_iterators/iter1.rs" },
  { name = "iter2", path = "../exercises/34_iterators/iter2.rs" },
  { name = "iter2_sol", path = "../solutions/34_iterators/iter2.rs" },
  { name = "iter3", path = "../exercises/34_iterators/iter3.rs" },
  { name = "iter3_sol", path = "../solutions/34_iterators/iter3.rs" },
  { name = "iter4", path = "../exercises/34_iterators/iter4.rs" },
  { name = "iter4_sol", path = "../solutions/34_iterators/iter4.rs" },
  { name = "err1", path = "../exercises/35_error_design/err1.rs" },
  { name = "err1_sol", path = "../solutions/35_error_design/err1.rs" },
  { name = "err2", path = "../exercises/35_error_design/err2.rs" },
  { name = "err2_sol", path = "../solutions/35_error_design/err2.rs" },
  { name = "err3", path = "../exercises/35_error_design/err3.rs" },
  { name = "err3_sol", path = "../solutions/35_error_design/err3.rs" },
  { name = "err4", path = "../exercises/35_error_design/err4.rs" },
  { name = "err4_sol", path = "../solutions/35_error_design/err4.rs" },
  { name = "err5", path = "../exercises/35_error_design/err5.rs" },
  { name = "err5_sol", path = "../solutions/35_error_design/err5.rs" },
  { name = "err6", path = "../exercises/35_error_design/err6.rs" },
  { name = "err6_sol", path = "../solutions/35_error_design/err6.rs" },
  { name = "coherence1", path = "../exercises/42_coherence/coherence1.rs" },
  { name = "coherence1_sol", path = "../solutions/42_coherence/coherence1.rs" },
  { name = "coherence2", path = "../exercises/42_coherence/coherence2.rs" },
  { name = "coherence2_sol", path = "../solutions/42_coherence/coherence2.rs" },
  { name = "coherence3", path = "../exercises/42_coherence/coherence3.rs" },
  { name = "coherence3_sol", path = "../solutions/42_coherence/coherence3.rs" },
  { name = "assoc1", path = "../exercises/43_assoc_types/assoc1.rs" },
  { name = "assoc1_sol", path = "../solutions/43_assoc_types/assoc1.rs" },
  { name = "assoc2", path = "../exercises/43_assoc_types/assoc2.rs" },
  { name = "assoc2_sol", path = "../solutions/43_assoc_types/assoc2.rs" },
  { name = "gat1", path = "../exercises/43_assoc_types/gat1.rs" },
  { name = "gat1_sol", path = "../solutions/43_assoc_types/gat1.rs" },
  { name = "contracts1", path = "../exercises/44_trait_contracts/contracts1.rs" },
  { name = "contracts1_sol", path = "../solutions/44_trait_contracts/contracts1.rs" },
  { name = "contracts2", path = "../exercises/44_trait_contracts/contracts2.rs" },
  { name = "contracts2_sol", path = "../solutions/44_trait_contracts/contracts2.rs" },
  { name = "contracts3", path = "../exercises/44_trait_contracts/contracts3.rs" },
  { name = "contracts3_sol", path = "../solutions/44_trait_contracts/contracts3.rs" },
  { name = "deref1", path = "../exercises/45_sized_deref/deref1.rs" },
  { name = "deref1_sol", path = "../solutions/45_sized_deref/deref1.rs" },
  { name = "deref2", path = "../exercises/45_sized_deref/deref2.rs" },
  { name = "deref2_sol", path = "../solutions/45_sized_deref/deref2.rs" },
  { name = "borrow1", path = "../exercises/45_sized_deref/borrow1.rs" },
  { name = "borrow1_sol", path = "../solutions/45_sized_deref/borrow1.rs" },
  { name = "cow1", path = "../exercises/45_sized_deref/cow1.rs" },
  { name = "cow1_sol", path = "../solutions/45_sized_deref/cow1.rs" },
  { name = "builder1", path = "../exercises/47_type_level/builder1.rs" },
  { name = "builder1_sol", path = "../solutions/47_type_level/builder1.rs" },
  { name = "typestate1", path = "../exercises/47_type_level/typestate1.rs" },
  { name = "typestate1_sol", path = "../solutions/47_type_level/typestate1.rs" },
  { name = "seams1", path = "../exercises/50_testing_seams/seams1.rs" },
  { name = "seams1_sol", path = "../solutions/50_testing_seams/seams1.rs" },
  { name = "seams2", path = "../exercises/50_testing_seams/seams2.rs" },
  { name = "seams2_sol", path = "../solutions/50_testing_seams/seams2.rs" },
  { name = "seams3", path = "../exercises/50_testing_seams/seams3.rs" },
  { name = "seams3_sol", path = "../solutions/50_testing_seams/seams3.rs" },
  { name = "linkedlist1", path = "../exercises/27_data_structures/linkedlist1.rs" },
  { name = "linkedlist1_sol", path = "../solutions/27_data_structures/linkedlist1.rs" },
  { name = "ringbuffer1", path = "../exercises/27_data_structures/ringbuffer1.rs" },
  { name = "ringbuffer1_sol", path = "../solutions/27_data_structures/ringbuffer1.rs" },
  { name = "hashtable1", path = "../exercises/27_data_structures/hashtable1.rs" },
  { name = "hashtable1_sol", path = "../solutions/27_data_structures/hashtable1.rs" },
  { name = "linkedlist2", path = "../exercises/27_data_structures/linkedlist2.rs" },
  { name = "linkedlist2_sol", path = "../solutions/27_data_structures/linkedlist2.rs" },
  { name = "linkedlist3", path = "../exercises/27_data_structures/linkedlist3.rs" },
  { name = "linkedlist3_sol", path = "../solutions/27_data_structures/linkedlist3.rs" },
  { name = "linkedlist4", path = "../exercises/27_data_structures/linkedlist4.rs" },
  { name = "linkedlist4_sol", path = "../solutions/27_data_structures/linkedlist4.rs" },
  { name = "arena1", path = "../exercises/59_arena/arena1.rs" },
  { name = "arena1_sol", path = "../solutions/59_arena/arena1.rs" },
  { name = "arena2", path = "../exercises/59_arena/arena2.rs" },
  { name = "arena2_sol", path = "../solutions/59_arena/arena2.rs" },
  { name = "lru1", path = "../exercises/60_lru_cache/lru1.rs" },
  { name = "lru1_sol", path = "../solutions/60_lru_cache/lru1.rs" },
  { name = "lru2", path = "../exercises/60_lru_cache/lru2.rs" },
  { name = "lru2_sol", path = "../solutions/60_lru_cache/lru2.rs" },
  { name = "lru3", path = "../exercises/60_lru_cache/lru3.rs" },
  { name = "lru3_sol", path = "../solutions/60_lru_cache/lru3.rs" },
  { name = "futures1", path = "../exercises/28_futures/futures1.rs" },
  { name = "futures1_sol", path = "../solutions/28_futures/futures1.rs" },
  { name = "futures2", path = "../exercises/28_futures/futures2.rs" },
  { name = "futures2_sol", path = "../solutions/28_futures/futures2.rs" },
  { name = "futures3", path = "../exercises/28_futures/futures3.rs" },
  { name = "futures3_sol", path = "../solutions/28_futures/futures3.rs" },
  { name = "futures4", path = "../exercises/28_futures/futures4.rs" },
  { name = "futures4_sol", path = "../solutions/28_futures/futures4.rs" },
  { name = "runtime1", path = "../exercises/29_async_runtime/runtime1.rs" },
  { name = "runtime1_sol", path = "../solutions/29_async_runtime/runtime1.rs" },
  { name = "runtime2", path = "../exercises/29_async_runtime/runtime2.rs" },
  { name = "runtime2_sol", path = "../solutions/29_async_runtime/runtime2.rs" },
  { name = "runtime3", path = "../exercises/29_async_runtime/runtime3.rs" },
  { name = "runtime3_sol", path = "../solutions/29_async_runtime/runtime3.rs" },
  { name = "runtime4", path = "../exercises/29_async_runtime/runtime4.rs" },
  { name = "runtime4_sol", path = "../solutions/29_async_runtime/runtime4.rs" },
  { name = "join1", path = "../exercises/57_async_combinators/join1.rs" },
  { name = "join1_sol", path = "../solutions/57_async_combinators/join1.rs" },
  { name = "select1", path = "../exercises/57_async_combinators/select1.rs" },
  { name = "select1_sol", path = "../solutions/57_async_combinators/select1.rs" },
  { name = "cancel1", path = "../exercises/57_async_combinators/cancel1.rs" },
  { name = "cancel1_sol", path = "../solutions/57_async_combinators/cancel1.rs" },
  { name = "oneshot1", path = "../exercises/58_leaf_futures/oneshot1.rs" },
  { name = "oneshot1_sol", path = "../solutions/58_leaf_futures/oneshot1.rs" },
  { name = "timer1", path = "../exercises/58_leaf_futures/timer1.rs" },
  { name = "timer1_sol", path = "../solutions/58_leaf_futures/timer1.rs" },
  { name = "yield1", path = "../exercises/58_leaf_futures/yield1.rs" },
  { name = "yield1_sol", path = "../solutions/58_leaf_futures/yield1.rs" },
  { name = "send_sync1", path = "../exercises/30_send_sync/send_sync1.rs" },
  { name = "send_sync1_sol", path = "../solutions/30_send_sync/send_sync1.rs" },
  { name = "send_sync2", path = "../exercises/30_send_sync/send_sync2.rs" },
  { name = "send_sync2_sol", path = "../solutions/30_send_sync/send_sync2.rs" },
  { name = "send_sync3", path = "../exercises/30_send_sync/send_sync3.rs" },
  { name = "send_sync3_sol", path = "../solutions/30_send_sync/send_sync3.rs" },
  { name = "async_send1", path = "../exercises/56_async_bounds/async_send1.rs" },
  { name = "async_send1_sol", path = "../solutions/56_async_bounds/async_send1.rs" },
  { name = "async_send2", path = "../exercises/56_async_bounds/async_send2.rs" },
  { name = "async_send2_sol", path = "../solutions/56_async_bounds/async_send2.rs" },
  { name = "async_send3", path = "../exercises/56_async_bounds/async_send3.rs" },
  { name = "async_send3_sol", path = "../solutions/56_async_bounds/async_send3.rs" },
  { name = "async_send4", path = "../exercises/56_async_bounds/async_send4.rs" },
  { name = "async_send4_sol", path = "../solutions/56_async_bounds/async_send4.rs" },
  { name = "scope1", path = "../exercises/51_scoped_threads/scope1.rs" },
  { name = "scope1_sol", path = "../solutions/51_scoped_threads/scope1.rs" },
  { name = "scope2", path = "../exercises/51_scoped_threads/scope2.rs" },
  { name = "scope2_sol", path = "../solutions/51_scoped_threads/scope2.rs" },
  { name = "scope3", path = "../exercises/51_scoped_threads/scope3.rs" },
  { name = "scope3_sol", path = "../solutions/51_scoped_threads/scope3.rs" },
  { name = "condvar1", path = "../exercises/52_condvar/condvar1.rs" },
  { name = "condvar1_sol", path = "../solutions/52_condvar/condvar1.rs" },
  { name = "condvar2", path = "../exercises/52_condvar/condvar2.rs" },
  { name = "condvar2_sol", path = "../solutions/52_condvar/condvar2.rs" },
  { name = "condvar3", path = "../exercises/52_condvar/condvar3.rs" },
  { name = "condvar3_sol", path = "../solutions/52_condvar/condvar3.rs" },
  { name = "deadlock1", path = "../exercises/53_lock_hazards/deadlock1.rs" },
  { name = "deadlock1_sol", path = "../solutions/53_lock_hazards/deadlock1.rs" },
  { name = "rwlock1", path = "../exercises/53_lock_hazards/rwlock1.rs" },
  { name = "rwlock1_sol", path = "../solutions/53_lock_hazards/rwlock1.rs" },
  { name = "channel1", path = "../exercises/54_channels/channel1.rs" },
  { name = "channel1_sol", path = "../solutions/54_channels/channel1.rs" },
  { name = "channel2", path = "../exercises/54_channels/channel2.rs" },
  { name = "channel2_sol", path = "../solutions/54_channels/channel2.rs" },
  { name = "channel3", path = "../exercises/54_channels/channel3.rs" },
  { name = "channel3_sol", path = "../solutions/54_channels/channel3.rs" },
  { name = "atomics1", path = "../exercises/36_atomics/atomics1.rs" },
  { name = "atomics1_sol", path = "../solutions/36_atomics/atomics1.rs" },
  { name = "atomics2", path = "../exercises/36_atomics/atomics2.rs" },
  { name = "atomics2_sol", path = "../solutions/36_atomics/atomics2.rs" },
  { name = "atomics3", path = "../exercises/36_atomics/atomics3.rs" },
  { name = "atomics3_sol", path = "../solutions/36_atomics/atomics3.rs" },
  { name = "atomics4", path = "../exercises/36_atomics/atomics4.rs" },
  { name = "atomics4_sol", path = "../solutions/36_atomics/atomics4.rs" },
  { name = "atomics5", path = "../exercises/36_atomics/atomics5.rs" },
  { name = "atomics5_sol", path = "../solutions/36_atomics/atomics5.rs" },
  { name = "debugging1", path = "../exercises/31_debugging/debugging1.rs" },
  { name = "debugging1_sol", path = "../solutions/31_debugging/debugging1.rs" },
  { name = "debugging2", path = "../exercises/31_debugging/debugging2.rs" },
  { name = "debugging2_sol", path = "../solutions/31_debugging/debugging2.rs" },
  { name = "debugging3", path = "../exercises/31_debugging/debugging3.rs" },
  { name = "debugging3_sol", path = "../solutions/31_debugging/debugging3.rs" },
  { name = "debugging4", path = "../exercises/31_debugging/debugging4.rs" },
  { name = "debugging4_sol", path = "../solutions/31_debugging/debugging4.rs" },
  { name = "debugging5", path = "../exercises/31_debugging/debugging5.rs" },
  { name = "debugging5_sol", path = "../solutions/31_debugging/debugging5.rs" },
  { name = "debugging6", path = "../exercises/31_debugging/debugging6.rs" },
  { name = "debugging6_sol", path = "../solutions/31_debugging/debugging6.rs" },
  { name = "debugging7", path = "../exercises/31_debugging/debugging7.rs" },
  { name = "debugging7_sol", path = "../solutions/31_debugging/debugging7.rs" },
  { name = "debugging8", path = "../exercises/31_debugging/debugging8.rs" },
  { name = "debugging8_sol", path = "../solutions/31_debugging/debugging8.rs" },
  { name = "window1", path = "../exercises/63_slices_strings/window1.rs" },
  { name = "window1_sol", path = "../solutions/63_slices_strings/window1.rs" },
  { name = "window2", path = "../exercises/63_slices_strings/window2.rs" },
  { name = "window2_sol", path = "../solutions/63_slices_strings/window2.rs" },
  { name = "window3", path = "../exercises/63_slices_strings/window3.rs" },
  { name = "window3_sol", path = "../solutions/63_slices_strings/window3.rs" },
  { name = "window4", path = "../exercises/63_slices_strings/window4.rs" },
  { name = "window4_sol", path = "../solutions/63_slices_strings/window4.rs" },
  { name = "checkedmath1", path = "../exercises/66_checked_math/checkedmath1.rs" },
  { name = "checkedmath1_sol", path = "../solutions/66_checked_math/checkedmath1.rs" },
  { name = "checkedmath2", path = "../exercises/66_checked_math/checkedmath2.rs" },
  { name = "checkedmath2_sol", path = "../solutions/66_checked_math/checkedmath2.rs" },
]

[package]
name = "exercises"
edition = "2024"
# Don't publish the exercises on crates.io!
publish = false

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lints.rust]
# You shouldn't write unsafe code in Rustlings!
unsafe_code = "forbid"
# You don't need unstable features in Rustlings and shouldn't rely on them while learning Rust.
unstable_features = "forbid"
# Dead code warnings can't be avoided in some exercises and might distract while learning.
dead_code = "allow"

[lints.clippy]
# You forgot a `todo!()`!
todo = "forbid"
# This can only happen by mistake in Rustlings.
empty_loop = "forbid"
# No infinite loops are needed in Rustlings.
infinite_loop = "deny"
# You shouldn't leak memory while still learning Rust!
mem_forget = "deny"
# Currently, there are no disallowed methods. This line avoids problems when developing Rustlings.
disallowed_methods = "allow"
