//! Lab · FFI: `unsafe extern` and `safe fn`, `repr(C)`, `CString`, trampolines
//!
//! Rust calls C, and C calls Rust, through the C ABI: integers, floats, raw
//! pointers, `repr(C)` structs and `extern "C"` function pointers. Nothing is
//! checked across that line. A declaration in an `extern` block is an
//! unchecked import (the linker matches the name, never the signature), which
//! is why edition 2024 makes you write `unsafe extern`. The lab has four parts,
//! one per question an FFI interview asks:
//!
//! 1. **Calling C** (`call_libc`): declare `strlen`, `abs`, `div`, `qsort` and
//!    `hypot`, get a `repr(C)` struct back by value, pass a Rust comparator to
//!    `qsort`. Which of them may be declared `safe fn`?
//! 2. **Strings and ownership** (`cstring_ownership`): `CString` vs `CStr`,
//!    `into_raw` / `from_raw`, a `#[unsafe(no_mangle)]` export, and the
//!    `as_ptr()` on a temporary that dangles. Who frees what?
//! 3. **Closures through a C callback** (`callback_trampoline`): a generic
//!    `extern "C"` trampoline behind a safe
//!    `for_each(&[i32], impl FnMut(i32))`, and what a panic in the closure
//!    does.
//! 4. **A C handle across threads** (`send_c_handle`): a non-thread-safe C
//!    context wrapped so that it is `Send` but not `Sync`, and shared through a
//!    `Mutex`.
//!
//! Compare with the graded exercises:
//!
//! - `30_send_sync/send_sync3`: the `assert_send` / `assert_sync` compile-time
//!   checks that part 4 uses.
//! - `56_async_bounds/async_send1`: std's `MutexGuard` is `Sync` but not
//!   `Send` (a pthread mutex must be unlocked by the thread that locked it).
//!   Part 4's `Handle` is the mirror image: `Send` but not `Sync`, like
//!   `Cell` and `RefCell`.
//! - `49_panics`: `panic1` catches a panic at a boundary, and the README's
//!   "Unwind or Abort" table lists the `extern "C"` abort that part 3 checks
//!   in a child process.
//! - `41_memory_layout/layout2`: what `repr(C)` does and does not guarantee.
//! - `33_closures`: every closure has its own type, which is what lets one
//!   generic trampoline serve them all. The `raw_waker` lab uses the same
//!   trick: a type-erased data pointer plus functions that know its real type.
//!
//! # The C side of this lab
//!
//! Part 1 calls the real C library (glibc's `libc` and `libm` on Linux,
//! `libSystem` on macOS). std links both already, so there is no build script.
//! Part 3 needs a C API that takes a callback plus a `void *user` pointer,
//! and libc has no portable one: `qsort_r` exists on glibc and on macOS with
//! different argument orders (glibc takes the comparator and then `arg`, and
//! calls `compar(a, b, arg)`; macOS takes `arg` first and calls
//! `compar(arg, a, b)`). Parts 2 and 4 need a library that hands out strings
//! and contexts it allocated itself. So the lab brings a tiny "C library" of
//! its own, written in Rust (the private module `fake_c`): `extern "C"`
//! functions exported under `ffi_lab_*` symbol names with
//! `#[unsafe(no_mangle)]`. The Rust side imports them back *by name* through
//! an `unsafe extern "C"` block (the private module `sys`), exactly as
//! bindings to a real C library (hand-written, or generated by bindgen) would.
//! In a real project the C code would be compiled by a build script (the `cc`
//! crate) or linked from a system library; keeping it in Rust means no C
//! compiler, and Miri can execute both sides.
//!
//! # 1. Calling C: what exactly is unsafe?
//!
//! - The `unsafe` in `unsafe extern "C" { .. }` is on the *declaration*: you
//!   promise that each symbol exists with exactly this signature and ABI.
//!   Nothing checks it, and a wrong signature is undefined behavior at the
//!   first call. Since edition 2024 a plain `extern` block is an error
//!   ("extern blocks must be unsafe").
//! - Every function in the block is unsafe to call unless it is marked
//!   `safe fn`. `safe fn` is a second promise: no argument values of the
//!   declared types can cause undefined behavior, and there is no other
//!   precondition (no pointer to validate, no global state to set up first,
//!   no thread restriction).
//! - [`hypot`] keeps that promise: every pair of `f64`s, NaNs and infinities
//!   included, has a defined result, and it takes no pointers. (On overflow
//!   ISO C lets it report a range error in the calling thread's `errno`, which
//!   is harmless.) std declares it (along with `tan`, `atan2`, `cosh` and
//!   friends) the same way, as `pub safe fn hypot(x: f64, y: f64) -> f64;` in
//!   `library/std/src/sys/cmath.rs`.
//! - `abs` and `div` look just as harmless, and are not. ISO C makes
//!   `abs(INT_MIN)` undefined (the result does not fit in an `int`), and
//!   `div(x, 0)` and `div(INT_MIN, -1)` too. Declared `safe fn`, they would
//!   let safe code call `abs(i32::MIN)`: an unsound binding, even though it
//!   compiles. So they stay `unsafe fn`, and the safe API is a checked wrapper
//!   that rejects the bad inputs before the call: [`checked_abs`] and
//!   [`checked_div`]. An unsafe raw binding plus a safe wrapper that
//!   establishes its preconditions is the shape of every `-sys` crate and the
//!   safe crate on top of it. (Real code would call `i32::checked_abs`; the
//!   pattern is the point.) Undefined behavior does not have to crash: on the
//!   aarch64 Mac this lab was written on, `abs(INT_MIN)` returns `INT_MIN` and
//!   `div(1, 0)` returns `{ quot: 0, rem: 1 }`, silently.
//! - `div` returns a `div_t` *by value*, so Rust needs a struct with the same
//!   layout: [`DivT`] is `#[repr(C)]`, which keeps the declared field order and
//!   C's padding. ISO C allows `quot` and `rem` "in either order", so the
//!   order is copied from the platform's header (macOS's and glibc's both put
//!   `quot` first; bindgen does this copying for you). Remove the `repr(C)`
//!   and rustc warns that the type "is not FFI-safe" (`improper_ctypes`).
//! - `qsort` takes a comparator `int (*)(const void *, const void *)`, and a
//!   Rust `unsafe extern "C" fn` fits it. A C function pointer that may be
//!   NULL is spelled `Option<fn>` (same size and ABI, `None` is NULL). The
//!   comparator uses `Ord::cmp`, never the C idiom `*a - *b`, which overflows
//!   for `i32::MIN - 1`. There is no `void *user` argument, so a comparator
//!   cannot capture anything, and closures are out (part 3 is for APIs that
//!   take one). A safe *generic* `qsort<T: Ord>` wrapper would even be
//!   unsound: ISO C makes an inconsistent comparator undefined behavior, while
//!   a safe `Ord` impl is allowed to be inconsistent (Rust's own `sort` stays
//!   memory safe even then). `i32`'s `Ord` is a total order, so [`qsort_i32`]
//!   is fine.
//! - `strlen` reads until it finds a NUL, so its argument must be
//!   NUL-terminated. `&CStr` guarantees exactly that, which makes [`c_strlen`]
//!   safe.
//!
//! # 2. Strings: who owns the bytes, and who frees them?
//!
//! - `CString::new(s)` takes the bytes of `s` (copying them if `s` is
//!   borrowed, like a `&str`) and appends a NUL. It fails with a `NulError`
//!   if `s` contains a NUL byte, because C would see the string end there:
//!   `nul_position()` says where, and `into_vec()` returns your bytes.
//! - `&CStr` is the borrowed view, C's `const char *`: `c"..."` literals, or
//!   `CStr::from_ptr` on a pointer C gave you. C strings are bytes, not UTF-8:
//!   `to_str()` fails on invalid UTF-8, while `to_string_lossy()` substitutes
//!   U+FFFD (and allocates only then).
//! - `as_ptr()` borrows: the pointer is valid while the `CString` lives. In
//!   `let p = CString::new(s).unwrap().as_ptr();` the temporary `CString` is
//!   dropped at the `;`, so `p` dangles. rustc warns
//!   (`dangling_pointers_from_temporaries`, warn by default) and Miri reports
//!   "memory access failed: allocN has been freed, so this pointer is
//!   dangling". [`c_len`] binds the `CString` to a local instead.
//! - `into_raw()` hands ownership to C, and the only correct way to free that
//!   pointer is `CString::from_raw` on the Rust side: C must give it back, and
//!   must not change the string's length meanwhile. C's `free` on it mixes
//!   allocators, which Miri reports as "deallocating allocN, which is Rust heap
//!   memory, using C heap deallocation operation". It can seem to work
//!   natively while Rust's global allocator happens to be `malloc`, and breaks
//!   once a program installs a different `#[global_allocator]`.
//! - The same rule runs the other way: memory the C library allocated goes
//!   back to the C library. `ffi_lab_greeting` returns a string that the
//!   caller must release with `ffi_lab_string_free`, and [`LibString`] is the
//!   owning Rust wrapper whose `Drop` does that, exactly once.
//! - `#[unsafe(no_mangle)]` exports a function under its plain name, so C can
//!   link to it. It is an unsafe *attribute* since edition 2024 (a bare
//!   `#[no_mangle]` is "unsafe attribute used without unsafe") because the
//!   name can collide with another symbol in the program, for example the C
//!   library's own `free`, and nothing checks that. Hence the `ffi_lab_`
//!   prefix on every symbol this lab exports.
//! - An exported function that dereferences a raw pointer argument is a
//!   `pub unsafe extern "C" fn` with a `# Safety` section. C callers do not
//!   see the `unsafe`; Rust callers do. For a function in the crate's public
//!   API, clippy's deny-by-default `not_unsafe_ptr_arg_deref` insists; it
//!   skips `fake_c`, a private module, so there the rule is kept by hand.
//!
//! # 3. A closure through `void (*cb)(void *user, int x)`
//!
//! A C function pointer is a bare code address: it cannot carry a closure's
//! captured state. C APIs solve this with the `void *user` pointer that they
//! pass back to every callback. So:
//!
//! 1. Put the closure (plus a slot for a panic payload) in a
//!    `TrampolineState<F>` on the Rust stack and pass a pointer to it as
//!    `user`.
//! 2. Pass `trampoline::<F>` as `cb`: a generic `unsafe extern "C" fn`,
//!    monomorphized once per closure type, so each copy knows what `user`
//!    really points to. It casts `user` back to `&mut TrampolineState<F>` and
//!    calls the closure.
//! 3. Wrap both in a safe function, [`for_each`], whose signature ties the
//!    pointer's lifetime to the call. That is sound only because this C
//!    function calls `cb` synchronously and keeps neither pointer after it
//!    returns. An API that stores the callback for later needs a heap
//!    allocation (`Box<F>`), a `'static` (and often `Send`) bound, and a
//!    matching "destroy" callback that frees it.
//!
//! A panic must not leave an `extern "C"` function: since Rust 1.81 it aborts
//! the whole process with "panic in a function that cannot unwind" (before
//! that it was undefined behavior). So `trampoline` wraps the call in
//! `catch_unwind`, stores the payload, skips the remaining callbacks, and
//! [`for_each_catching`] returns `Err(payload)` once C has returned;
//! [`for_each`] resumes the panic on the Rust side with `resume_unwind`. The
//! alternative is the `"C-unwind"` ABI (Rust 1.71): when both the callback and
//! the C function are declared `extern "C-unwind"`, a panic may unwind
//! through the foreign frames ([`for_each_unwind`]). That is only defined if
//! the foreign code was built to be unwound through (C++, or C compiled with
//! `-fexceptions`), which is why catching at the boundary is the usual
//! answer. The broken trampoline, without `catch_unwind`, is kept in the
//! tests' `broken` module; a test runs it in a child process and checks that
//! the process died of `SIGABRT` with that message.
//!
//! # 4. A non-thread-safe C handle: `Send`, not `Sync`
//!
//! The pretend C library hands out a `ctx *` whose functions do no locking.
//! Its (pretend) documentation says: "a context may be used from any thread,
//! but calls on one context must not overlap". [`Ctx`] is declared the way
//! the Rustonomicon recommends for an opaque C type, and [`Handle`] owns one
//! `ctx *`, freeing it in `Drop`.
//!
//! - `Handle(NonNull<Ctx>)` starts out neither `Send` nor `Sync`, because raw
//!   pointers, `NonNull` included, are neither. Auto traits cannot know what a
//!   pointer points to, so the author must decide.
//! - `unsafe impl Send for Handle` is justified by the contract: the context
//!   has no thread affinity, and moving the only `Handle` moves the right to
//!   call into it. A library whose objects must stay on their creating thread
//!   (GUI toolkits whose objects belong to the main thread, or a library that
//!   keeps its state in thread-local storage) would get no `Send` either.
//! - `Sync` would be unsound. `Handle: Sync` makes `&Handle: Send`, so safe
//!   code could share one handle between threads (`Arc<Handle>`, scoped
//!   threads) and call [`Handle::bump`] on the same context from two threads
//!   at once: a data race inside C, which is undefined behavior. The tests'
//!   `broken::SyncHandle` does exactly that, and Miri reports "Data race
//!   detected". (If every method took `&mut self`, a shared `&Handle` could do
//!   nothing and `Sync` would be harmless; that is the idea behind the
//!   unstable `std::sync::SyncView`, formerly `Exclusive`.)
//! - To share it, wrap it: `Mutex<T>` is `Sync` whenever `T: Send`, and the
//!   lock serializes the calls. So `Arc<Mutex<Handle>>` is the thread-safe
//!   handle, and the `unsafe impl Send` is what makes it possible.
//!
//! # Invariants
//!
//! - Every pointer given to C is valid for exactly what the function reads or
//!   writes, for the whole call: `&[i32]` becomes a (pointer, length) pair,
//!   `&CStr` a NUL-terminated string. An empty slice's pointer is dangling
//!   (non-NULL, aligned, pointing at nothing), so it goes only to functions
//!   documented to read nothing when the length is 0 (`ffi_lab_for_each`).
//!   The C standard library makes no such promise (its functions want valid
//!   pointers even for zero elements), so `qsort_i32` never calls `qsort` for
//!   fewer than two elements.
//! - Memory goes back to the allocator it came from: `CString::into_raw` to
//!   `CString::from_raw`, library strings to `ffi_lab_string_free`, a context
//!   to `ffi_lab_ctx_free`, each exactly once.
//! - No panic crosses an `extern "C"` boundary: trampolines catch, and the
//!   exported functions never panic (a failure becomes NULL).
//! - A trampoline's `user` points to a live `TrampolineState<F>` for exactly
//!   the `F` it was instantiated with.
//! - Calls on one context never overlap: `Handle` is `!Sync`.
//! - `safe fn` only for foreign functions with no preconditions at all.
//!
//! # Sharpest question
//!
//! *How do you pass a Rust closure to a C API that takes
//! `void (*cb)(void*, int)` plus a `void* user` pointer, and what happens if
//! the closure panics?* Pass a pointer to the closure (in a state struct) as
//! `user`, and a generic `extern "C" fn trampoline<F: FnMut(i32)>` as `cb`;
//! the trampoline casts `user` back to `&mut F` and calls it. Hide both behind
//! a safe function that borrows the closure for the duration of the call,
//! which is sound only if C does not keep the pointers after returning (if it
//! does, box the closure and free it from a destroy callback). A panic that
//! reaches the end of an `extern "C"` function aborts the process (Rust 1.81
//! and later; undefined behavior before). So catch it with `catch_unwind`
//! inside the trampoline, stop or skip the remaining callbacks, and resume the
//! panic (or return an error) on the Rust side after the C function returns.
//! Only when the foreign code supports unwinding may both sides be declared
//! `extern "C-unwind"` and the panic unwind through.
//!
//! # What runs under Miri
//!
//! Miri can call `strlen`, `hypot` and the `ffi_lab_*` functions (it
//! resolves an `extern` declaration to a `#[no_mangle]` Rust function), so
//! parts 2 to 4 run under Miri, with its leak and double-free checks, all but
//! the child-process test. It has no shim for `abs`, `div` or `qsort`
//! ("unsupported operation: can't call foreign function `abs` on OS `linux`",
//! or `macos`), and it cannot spawn processes, so those tests are
//! `#[cfg_attr(miri, ignore)]`. This was checked for both the macOS host and
//! the Linux target that CI uses (Miri can interpret another target:
//! `cargo +nightly miri test --target x86_64-unknown-linux-gnu`).
//!
//! # Run it
//!
//! ```text
//! cargo test --manifest-path deep-dive/Cargo.toml ffi_lab
//! MIRIFLAGS="-Zmiri-strict-provenance" cargo +nightly miri test --manifest-path deep-dive/Cargo.toml ffi_lab
//! ```
//!
//! The three `#[ignore]`d undefined-behavior demonstrations run only under
//! Miri (natively they return early instead of executing it):
//!
//! ```text
//! cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::dangling_as_ptr_is_a_use_after_free
//! cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::c_free_on_a_cstring_mixes_allocators
//! cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::sync_handle_lets_two_threads_race
//! ```
//!
//! Stable rustdoc does not check the error codes on `compile_fail` doctests,
//! so every one below is paired with a positive control that differs
//! minimally. Nightly rustdoc does check them, and the `deep-dive-miri` CI job
//! runs the doctests on nightly, so there the codes are enforced too:
//!
//! ```text
//! cargo +nightly test --manifest-path deep-dive/Cargo.toml --doc ffi_lab
//! ```
//!
//! # Try it
//!
//! - Delete the `unsafe` in front of the libc `extern "C"` block below: the
//!   build fails with "extern blocks must be unsafe" (and, once each for
//!   `safe fn hypot`, `unsafe fn abs` and `unsafe fn div`, "items in `extern`
//!   blocks without an `unsafe` qualifier cannot have safety qualifiers").
//! - Change `unsafe fn abs` to `safe fn abs`. It compiles (rustc only warns
//!   that the `unsafe` block in `checked_abs` is now unnecessary), and safe
//!   code can call `abs(i32::MIN)`: the compiler cannot tell a true `safe fn`
//!   promise from a false one.
//! - Remove `#[repr(C)]` from `DivT`: rustc warns `improper_ctypes`
//!   ("`extern` block uses type `DivT`, which is not FFI-safe"; clippy
//!   prints the path, `ffi_lab::DivT`), which the CI's `clippy -D warnings`
//!   turns into an error.
//! - Replace the body of `trampoline` with `{}`, as an unfinished stub would
//!   be: `for_each_passes_every_value_to_the_closure` fails with an empty
//!   `Vec`.
//! - Call `(state.f)(x)` in `trampoline` without the `catch_unwind`: the whole
//!   test binary dies of `SIGABRT` at the first test whose closure panics,
//!   with "panic in a function that cannot unwind".
//! - Watch the abort that `panic_through_extern_c_aborts_the_process` checks,
//!   natively and under Miri ("abnormal termination: the program aborted
//!   execution"):
//!
//!   ```text
//!   FFI_LAB_ABORT_CHILD=1 cargo test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::child_panics_through_extern_c --nocapture
//!   FFI_LAB_ABORT_CHILD=1 MIRIFLAGS=-Zmiri-env-forward=FFI_LAB_ABORT_CHILD cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::child_panics_through_extern_c
//!   ```
//!
//! - Comment out the `ffi_lab_string_free` call in `LibString`'s `Drop`:
//!   `greeting_is_freed_by_the_library_exactly_once` fails (2 strings still
//!   live), and under Miri the `greeting` doctest, which counts nothing,
//!   fails too: "memory leaked: allocN (Rust heap, size: 15, align: 1)".
//! - Delete `unsafe impl Send for Handle`: the tests no longer compile
//!   (E0277, "`NonNull<Ctx>` cannot be sent between threads safely"), and
//!   the `Mutex<Handle>` doctest on [`Handle`] fails the same way.
//! - Add `unsafe impl Sync for Handle {}`: the `assert_sync::<Handle>()`
//!   `compile_fail` doctest on [`Handle`] now compiles, and `cargo test --doc`
//!   reports "Test compiled successfully, but it's marked `compile_fail`".
//!
//! # Edition 2024 rules, checked by doctests
//!
//! A plain `extern` block is rejected ("extern blocks must be unsafe"):
//!
//! ```compile_fail
//! use std::ffi::c_char;
//! extern "C" {
//!     fn strlen(s: *const c_char) -> usize;
//! }
//! // SAFETY: a `c"..."` literal is NUL-terminated and lives forever.
//! assert_eq!(unsafe { strlen(c"hi".as_ptr()) }, 2);
//! ```
//!
//! Calling a foreign function that is not a `safe fn` outside an `unsafe`
//! block is E0133:
//!
//! ```compile_fail,E0133
//! use std::ffi::c_char;
//! unsafe extern "C" {
//!     fn strlen(s: *const c_char) -> usize;
//! }
//! assert_eq!(strlen(c"hi".as_ptr()), 2);
//! ```
//!
//! The positive control for both, one `unsafe` away from each:
//!
//! ```
//! use std::ffi::c_char;
//! unsafe extern "C" {
//!     fn strlen(s: *const c_char) -> usize;
//! }
//! // SAFETY: a `c"..."` literal is NUL-terminated and lives forever.
//! assert_eq!(unsafe { strlen(c"hi".as_ptr()) }, 2);
//! ```
//!
//! A `safe fn` is called like any Rust function:
//!
//! ```
//! unsafe extern "C" {
//!     safe fn hypot(x: f64, y: f64) -> f64;
//! }
//! assert!((hypot(3.0, 4.0) - 5.0).abs() < 1e-9);
//! ```
//!
//! And the compiler takes that promise on trust: this BROKEN binding
//! compiles, and hands safe code C's undefined `abs(INT_MIN)` (the function
//! is never called here, so the doctest runs under Miri too):
//!
//! ```
//! use std::ffi::c_int;
//! unsafe extern "C" {
//!     // BROKEN on purpose: a false promise, since `abs(INT_MIN)` is UB.
//!     safe fn abs(j: c_int) -> c_int;
//! }
//! fn looks_safe() -> c_int {
//!     abs(c_int::MIN) // no `unsafe` anywhere, yet undefined behavior
//! }
//! let _unsound: fn() -> c_int = looks_safe;
//! ```
//!
//! `no_mangle` must be written as an unsafe attribute ("unsafe attribute used
//! without unsafe"):
//!
//! ```compile_fail
//! #[no_mangle]
//! pub extern "C" fn ffi_lab_doctest_answer() -> i32 {
//!     42
//! }
//! ```
//!
//! Positive control:
//!
//! ```
//! #[unsafe(no_mangle)]
//! pub extern "C" fn ffi_lab_doctest_answer() -> i32 {
//!     42
//! }
//! assert_eq!(ffi_lab_doctest_answer(), 42);
//! ```

use std::any::Any;
use std::ffi::{CStr, CString, NulError, c_char, c_int, c_void};
use std::marker::{PhantomData, PhantomPinned};
use std::mem::offset_of;
use std::panic::{self, AssertUnwindSafe};
use std::ptr::NonNull;

// ---------------------------------------------------------------------------
// Part 1 · call_libc: real C library functions
// ---------------------------------------------------------------------------

/// C's `div_t`: `typedef struct { int quot; int rem; } div_t;`, copied field
/// by field from the platform header. `#[repr(C)]` keeps this order and C's
/// padding; the default `repr(Rust)` would promise neither.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DivT {
    pub quot: c_int,
    pub rem: c_int,
}

// Layout guards, checked at compile time: two `int`s, `quot` first, no
// padding (`41_memory_layout/layout2` uses the same idiom).
const _: () = assert!(size_of::<DivT>() == 2 * size_of::<c_int>());
const _: () = assert!(align_of::<DivT>() == align_of::<c_int>());
const _: () = assert!(offset_of!(DivT, quot) == 0);
const _: () = assert!(offset_of!(DivT, rem) == size_of::<c_int>());

/// qsort's comparator type: `int (*compar)(const void *, const void *)`.
/// `Option` because a C function pointer can be NULL; `Option<fn>` has the
/// pointer's size and ABI, with `None` as NULL.
type QsortCompare = Option<unsafe extern "C" fn(*const c_void, *const c_void) -> c_int>;

// The `unsafe` promises that these symbols exist in the C library with
// exactly these signatures; the linker checks only the names.
unsafe extern "C" {
    /// `double hypot(double x, double y);` Sound for every input (NaN and
    /// infinities included) and it takes no pointers, so it is a `safe fn`:
    /// callable without `unsafe`. std declares it the same way.
    ///
    /// ```
    /// use deep_dive::ffi_lab::hypot;
    ///
    /// let h = hypot(3.0, 4.0); // no `unsafe` block needed
    /// assert!((h - 5.0).abs() < 1e-9);
    /// ```
    // Microsoft's C runtime exports this function as `_hypot`; std's own
    // declaration renames it the same way. `link_name` binds a Rust name to a
    // different symbol.
    #[cfg_attr(target_env = "msvc", link_name = "_hypot")]
    pub safe fn hypot(x: f64, y: f64) -> f64;

    /// `int abs(int j);` Undefined for `INT_MIN`, so NOT a `safe fn`.
    unsafe fn abs(j: c_int) -> c_int;

    /// `div_t div(int numer, int denom);` Undefined for `denom == 0` and for
    /// `INT_MIN / -1`, so NOT a `safe fn`.
    unsafe fn div(numer: c_int, denom: c_int) -> DivT;

    /// `size_t strlen(const char *s);` `s` must be NUL-terminated.
    fn strlen(s: *const c_char) -> usize;

    /// `void qsort(void *base, size_t nmemb, size_t size, compar);`
    fn qsort(base: *mut c_void, nmemb: usize, size: usize, compar: QsortCompare);
}

/// `abs` behind a check: `None` for `i32::MIN`, whose absolute value does not
/// fit in an `i32` (C's `abs` is undefined there).
pub fn checked_abs(x: i32) -> Option<i32> {
    if x == i32::MIN {
        return None;
    }
    // SAFETY: `x != INT_MIN`, so `|x|` fits in an `int`; `abs` has no other
    // precondition.
    Some(unsafe { abs(x) })
}

/// `div` behind a check: `None` for a zero divisor and for `i32::MIN / -1`,
/// the two inputs for which C's `div` is undefined. Like Rust's `/` and `%`,
/// C99 truncates toward zero, so `div(-7, 2)` is `{ quot: -3, rem: -1 }`.
pub fn checked_div(numer: i32, denom: i32) -> Option<DivT> {
    if denom == 0 || (numer == i32::MIN && denom == -1) {
        return None;
    }
    // SAFETY: `denom != 0` and the quotient is not `INT_MIN / -1`, so both
    // parts of the result fit in an `int`.
    Some(unsafe { div(numer, denom) })
}

/// C's `strlen`, made safe by its argument type: a `&CStr` is always
/// NUL-terminated. Counts bytes, not characters.
pub fn c_strlen(s: &CStr) -> usize {
    // SAFETY: `s.as_ptr()` points to a NUL-terminated string that stays
    // borrowed, so alive and unchanged, for the whole call.
    unsafe { strlen(s.as_ptr()) }
}

/// The comparator handed to `qsort`. Returns the sign of `a - b` without
/// computing `a - b`: `i32::MIN - 1` overflows, the classic C comparator bug.
///
/// # Safety
///
/// `a` and `b` must point to initialized `i32`s that nothing writes to during
/// the call.
unsafe extern "C" fn compare_i32(a: *const c_void, b: *const c_void) -> c_int {
    // SAFETY: only `qsort_i32` passes this function to qsort, for an `[i32]`,
    // and ISO C guarantees that qsort calls it with pointers to elements of
    // that array: aligned, initialized `i32`s, which qsort does not write to
    // while the comparator runs.
    let a = unsafe { *a.cast::<i32>() };
    // SAFETY: as for `a`.
    let b = unsafe { *b.cast::<i32>() };
    a.cmp(&b) as c_int
}

/// Sorts `xs` with C's `qsort` and the Rust comparator `compare_i32`.
pub fn qsort_i32(xs: &mut [i32]) {
    // C requires valid pointers even for zero elements, and an empty slice's
    // pointer is dangling, so short slices never reach C (nothing to sort).
    if xs.len() < 2 {
        return;
    }
    // SAFETY: `base` points to `xs.len()` initialized elements of
    // `size_of::<i32>()` bytes each, borrowed mutably for the whole call.
    // `compare_i32` reads exactly such elements and is a total order, as ISO C
    // requires. qsort only permutes the elements (byte copies are valid moves
    // for `i32`) and keeps no pointer after it returns.
    unsafe {
        qsort(
            xs.as_mut_ptr().cast(),
            xs.len(),
            size_of::<i32>(),
            Some(compare_i32),
        );
    }
}

// ---------------------------------------------------------------------------
// The pretend C library (parts 2 to 4)
// ---------------------------------------------------------------------------

/// The library's context type, as its C header declares it:
/// `typedef struct ctx ctx;`, an incomplete type that Rust only ever sees
/// behind a pointer. This is the Rustonomicon's recipe for an opaque type: a
/// private field means it cannot be constructed outside this module, and the
/// marker makes it neither `Send`, `Sync` nor `Unpin`.
#[repr(C)]
pub struct Ctx {
    _data: (),
    _marker: PhantomData<(*mut u8, PhantomPinned)>,
}

/// Stand-in for a C library, written in Rust so that the lab needs no C
/// compiler and Miri can run it. Everything here is reached from the rest of
/// the file only through the symbol names imported in `sys`.
mod fake_c {
    use super::Ctx;
    use std::ffi::{CStr, CString, c_char, c_int, c_void};
    use std::ptr;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// The state behind a `ctx *`: a plain `int` with no locking, so NOT
    /// thread-safe. Calls on one context must not overlap.
    struct CtxState {
        count: c_int,
    }

    /// A debug counter of live allocations (contexts plus strings), as some C
    /// libraries keep in debug builds: the tests read it to prove that every
    /// allocation is freed exactly once.
    static LIVE: AtomicUsize = AtomicUsize::new(0);

    /// `size_t ffi_lab_live_allocations(void);`
    #[unsafe(no_mangle)]
    pub extern "C" fn ffi_lab_live_allocations() -> usize {
        LIVE.load(Ordering::SeqCst)
    }

    /// `ctx *ffi_lab_ctx_new(void);` Never returns NULL (Rust's allocator
    /// aborts on out-of-memory).
    #[unsafe(no_mangle)]
    pub extern "C" fn ffi_lab_ctx_new() -> *mut Ctx {
        LIVE.fetch_add(1, Ordering::SeqCst);
        Box::into_raw(Box::new(CtxState { count: 0 })).cast()
    }

    /// `int ffi_lab_ctx_bump(ctx *c);` Increments the counter and returns the
    /// new value. Not thread-safe: a non-atomic read-modify-write.
    ///
    /// # Safety
    ///
    /// `c` must come from `ffi_lab_ctx_new`, not be freed yet, and no other
    /// call on the same `c` may run at the same time.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn ffi_lab_ctx_bump(c: *mut Ctx) -> c_int {
        let state = c.cast::<CtxState>();
        // SAFETY: per the contract, `state` points to a live `CtxState` from
        // `ffi_lab_ctx_new`, and no other call on it runs concurrently.
        let old = unsafe { (*state).count };
        // Wrapping, where C's signed overflow would be undefined and a
        // debug-build panic would abort (this is an `extern "C"` fn).
        let new = old.wrapping_add(1);
        // SAFETY: as for the read; nothing else accessed it in between.
        unsafe { (*state).count = new };
        new
    }

    /// `void ffi_lab_ctx_free(ctx *c);`
    ///
    /// # Safety
    ///
    /// `c` must come from `ffi_lab_ctx_new` and not be freed yet; it must not
    /// be used afterwards.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn ffi_lab_ctx_free(c: *mut Ctx) {
        // SAFETY: `c` came from `Box::into_raw` in `ffi_lab_ctx_new` and is
        // freed exactly once, here.
        drop(unsafe { Box::from_raw(c.cast::<CtxState>()) });
        LIVE.fetch_sub(1, Ordering::SeqCst);
    }

    /// `char *ffi_lab_greeting(const char *name);` Returns a new string
    /// `"Hello, <name>!"` that the caller owns and must release with
    /// `ffi_lab_string_free` (never with C's `free`). Returns NULL if `name`
    /// is NULL. Invalid UTF-8 in `name` becomes U+FFFD.
    ///
    /// # Safety
    ///
    /// `name` must be NULL or point to a NUL-terminated string that stays
    /// unchanged during the call.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn ffi_lab_greeting(name: *const c_char) -> *mut c_char {
        if name.is_null() {
            return ptr::null_mut();
        }
        // SAFETY: `name` is non-NULL, and the caller promises it points to a
        // NUL-terminated string that does not change during this call.
        let name = unsafe { CStr::from_ptr(name) };
        let greeting = format!("Hello, {}!", name.to_string_lossy());
        // A `CStr` holds no NUL byte, and neither does the rest, so `new`
        // cannot fail. Still, a failure becomes NULL rather than a panic,
        // which could not leave this `extern "C"` function anyway.
        match CString::new(greeting) {
            Ok(s) => {
                LIVE.fetch_add(1, Ordering::SeqCst);
                s.into_raw()
            }
            Err(_) => ptr::null_mut(),
        }
    }

    /// `void ffi_lab_string_free(char *s);` Frees a string returned by
    /// `ffi_lab_greeting`. NULL is a no-op, as for C's `free`.
    ///
    /// # Safety
    ///
    /// `s` must be NULL, or come from `ffi_lab_greeting`, not be freed yet,
    /// and still have its original length.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn ffi_lab_string_free(s: *mut c_char) {
        if s.is_null() {
            return;
        }
        // SAFETY: `s` came from `CString::into_raw` in `ffi_lab_greeting`, is
        // freed exactly once, here, and its length is unchanged.
        drop(unsafe { CString::from_raw(s) });
        LIVE.fetch_sub(1, Ordering::SeqCst);
    }

    /// `void ffi_lab_for_each(const int *xs, size_t len,
    ///                        void (*cb)(void *user, int x), void *user);`
    /// Calls `cb(user, x)` for every element, in order, before returning, and
    /// keeps neither `cb` nor `user` afterwards. A NULL `cb` does nothing.
    ///
    /// # Safety
    ///
    /// `xs` must be valid for reading `len` ints, and `cb` must be safe to call
    /// with `user` and each element.
    #[unsafe(no_mangle)]
    pub unsafe extern "C" fn ffi_lab_for_each(
        xs: *const c_int,
        len: usize,
        cb: Option<unsafe extern "C" fn(user: *mut c_void, x: c_int)>,
        user: *mut c_void,
    ) {
        let Some(cb) = cb else { return };
        for i in 0..len {
            // SAFETY: the caller promises `xs` is valid for `len` reads, and
            // `i < len`.
            let x = unsafe { xs.add(i).read() };
            // SAFETY: the caller promises `cb` may be called with `user`.
            unsafe { cb(user, x) };
        }
    }

    /// The same function for a library that allows unwinding through it (a
    /// C++ library, or C compiled with `-fexceptions`): both it and its
    /// callback use the `"C-unwind"` ABI, so a panic in `cb` unwinds through
    /// this frame to its caller.
    ///
    /// # Safety
    ///
    /// As for `ffi_lab_for_each`.
    #[unsafe(no_mangle)]
    pub unsafe extern "C-unwind" fn ffi_lab_for_each_unwind(
        xs: *const c_int,
        len: usize,
        cb: Option<unsafe extern "C-unwind" fn(user: *mut c_void, x: c_int)>,
        user: *mut c_void,
    ) {
        let Some(cb) = cb else { return };
        for i in 0..len {
            // SAFETY: the caller promises `xs` is valid for `len` reads, and
            // `i < len`.
            let x = unsafe { xs.add(i).read() };
            // SAFETY: the caller promises `cb` may be called with `user`.
            unsafe { cb(user, x) };
        }
    }
}

/// The bindings: what a `-sys` crate (or bindgen) would give you for the
/// library above. The functions are found by symbol name at link time, exactly
/// as if `fake_c` were compiled C.
mod sys {
    use super::Ctx;
    use std::ffi::{c_char, c_int, c_void};

    /// `void (*cb)(void *user, int x)`, nullable.
    pub type Callback = Option<unsafe extern "C" fn(user: *mut c_void, x: c_int)>;
    /// The same callback in the `"C-unwind"` ABI.
    pub type CallbackUnwind = Option<unsafe extern "C-unwind" fn(user: *mut c_void, x: c_int)>;

    unsafe extern "C" {
        // No arguments and no preconditions: honest `safe fn`s.
        pub safe fn ffi_lab_live_allocations() -> usize;
        pub safe fn ffi_lab_ctx_new() -> *mut Ctx;

        pub fn ffi_lab_ctx_bump(c: *mut Ctx) -> c_int;
        pub fn ffi_lab_ctx_free(c: *mut Ctx);
        pub fn ffi_lab_greeting(name: *const c_char) -> *mut c_char;
        pub fn ffi_lab_string_free(s: *mut c_char);
        pub fn ffi_lab_for_each(xs: *const c_int, len: usize, cb: Callback, user: *mut c_void);
    }

    unsafe extern "C-unwind" {
        pub fn ffi_lab_for_each_unwind(
            xs: *const c_int,
            len: usize,
            cb: CallbackUnwind,
            user: *mut c_void,
        );
    }
}

/// How many contexts and library strings are currently allocated (the pretend
/// library's debug counter).
pub fn live_allocations() -> usize {
    sys::ffi_lab_live_allocations()
}

// ---------------------------------------------------------------------------
// Part 2 · cstring_ownership
// ---------------------------------------------------------------------------

/// The byte length of `s` as C's `strlen` sees it. The `CString` is bound to a
/// local, so it lives until the end of the function and the pointer stays
/// valid for the call. `Err` if `s` contains a NUL byte.
pub fn c_len(s: &str) -> Result<usize, NulError> {
    let owned = CString::new(s)?;
    Ok(c_strlen(&owned))
}

/// A string allocated by the pretend C library, freed by it in `Drop`: the
/// foreign-allocation counterpart of `CString`. Never pass its pointer to C's
/// `free` or to `CString::from_raw`; only the library that allocated it may
/// free it.
pub struct LibString(NonNull<c_char>);

impl LibString {
    /// Borrows the string. The `&CStr` cannot outlive `self`.
    pub fn as_c_str(&self) -> &CStr {
        // SAFETY: the pointer came from `ffi_lab_greeting`, is non-NULL,
        // NUL-terminated and not freed before `self` is dropped; nothing
        // writes to it meanwhile.
        unsafe { CStr::from_ptr(self.0.as_ptr()) }
    }
}

impl Drop for LibString {
    fn drop(&mut self) {
        // SAFETY: the pointer came from `ffi_lab_greeting` and is released
        // exactly once, here, by the library that allocated it.
        unsafe { sys::ffi_lab_string_free(self.0.as_ptr()) };
    }
}

/// Asks the pretend C library for `"Hello, <name>!"` and takes ownership of
/// the result. `None` if the library returned NULL.
///
/// ```
/// use deep_dive::ffi_lab::greeting;
///
/// let s = greeting(c"Ferris").unwrap();
/// assert_eq!(s.as_c_str(), c"Hello, Ferris!");
/// // `s` goes back to the library (ffi_lab_string_free) here.
/// ```
pub fn greeting(name: &CStr) -> Option<LibString> {
    // SAFETY: `name.as_ptr()` is a NUL-terminated string, borrowed (so
    // unchanged) for the whole call.
    let raw = unsafe { sys::ffi_lab_greeting(name.as_ptr()) };
    NonNull::new(raw).map(LibString)
}

// ---------------------------------------------------------------------------
// Part 3 · callback_trampoline
// ---------------------------------------------------------------------------

/// What `user` points to while C runs our callback: the closure, plus the
/// payload of a panic caught in it.
struct TrampolineState<F> {
    f: F,
    panic: Option<Box<dyn Any + Send>>,
}

/// The `cb` handed to C. One copy per closure type `F` (monomorphization),
/// so each copy knows what `user` really points to.
///
/// # Safety
///
/// `user` must point to a live `TrampolineState<F>` for this very `F`, not
/// accessed by anything else during the call.
unsafe extern "C" fn trampoline<F: FnMut(i32)>(user: *mut c_void, x: c_int) {
    // SAFETY: `for_each_catching` passes a pointer to its local
    // `TrampolineState<F>` and does not touch it until the C function
    // returns; the C function calls us synchronously, one call at a time, so
    // this `&mut` is unique while it exists.
    let state = unsafe { &mut *user.cast::<TrampolineState<F>>() };
    if state.panic.is_some() {
        // An earlier call panicked, and this C API cannot be told to stop:
        // skip the remaining elements.
        return;
    }
    // A panic must not unwind out of an `extern "C"` function (the process
    // would abort), so catch it here and carry it back to Rust. Asserting
    // unwind safety is fine: nothing here is used again after a panic, except
    // the payload slot.
    if let Err(payload) = panic::catch_unwind(AssertUnwindSafe(|| (state.f)(x))) {
        state.panic = Some(payload);
    }
}

/// Calls `f` on every element of `xs` through the C function
/// `ffi_lab_for_each`. Returns `Err(payload)` if `f` panicked; the elements
/// after the panicking one are skipped. `f` is dropped exactly once, either
/// way.
pub fn for_each_catching<F: FnMut(i32)>(xs: &[i32], f: F) -> Result<(), Box<dyn Any + Send>> {
    let mut state = TrampolineState { f, panic: None };
    // SAFETY: `xs.as_ptr()` is valid for `xs.len()` reads (an `i32` is a C
    // `int`). `trampoline::<F>` matches the `TrampolineState<F>` behind
    // `user`, which lives on this stack frame until after the call and is not
    // touched by us meanwhile. `ffi_lab_for_each` calls back synchronously and
    // keeps neither pointer after it returns.
    unsafe {
        sys::ffi_lab_for_each(
            xs.as_ptr(),
            xs.len(),
            Some(trampoline::<F>),
            (&raw mut state).cast(),
        );
    }
    match state.panic {
        Some(payload) => Err(payload),
        None => Ok(()),
    }
}

/// The safe API: calls `f` on every element of `xs` through C, and if `f`
/// panics, the panic continues on the Rust side (`resume_unwind`) once the C
/// function has returned, as if C were not there.
///
/// ```
/// use deep_dive::ffi_lab::for_each;
///
/// let mut sum = 0;
/// for_each(&[1, 2, 3], |x| sum += x);
/// assert_eq!(sum, 6);
/// ```
pub fn for_each<F: FnMut(i32)>(xs: &[i32], f: F) {
    if let Err(payload) = for_each_catching(xs, f) {
        panic::resume_unwind(payload);
    }
}

/// The `"C-unwind"` trampoline: no `catch_unwind`, because this ABI lets a
/// panic unwind out of it.
///
/// # Safety
///
/// `user` must point to a live `F`, not accessed by anything else during the
/// call.
unsafe extern "C-unwind" fn trampoline_unwind<F: FnMut(i32)>(user: *mut c_void, x: c_int) {
    // SAFETY: `for_each_unwind` passes a pointer to its local `F` and does not
    // touch it until the C function returns (or unwinds).
    let f = unsafe { &mut *user.cast::<F>() };
    f(x);
}

/// Like [`for_each`], but through `ffi_lab_for_each_unwind`, whose ABI is
/// `"C-unwind"`: a panic in `f` unwinds straight through the foreign frame.
/// Only valid for foreign code built to be unwound through; the stand-in
/// library is Rust, so it is.
pub fn for_each_unwind<F: FnMut(i32)>(xs: &[i32], mut f: F) {
    // SAFETY: as in `for_each_catching`: `xs` is valid for `xs.len()` reads,
    // `trampoline_unwind::<F>` matches the `F` behind `user`, which outlives
    // the call, and the callee keeps no pointer. Both sides are `"C-unwind"`,
    // so a panic may cross them; `f` is then dropped by this frame's unwind.
    unsafe {
        sys::ffi_lab_for_each_unwind(
            xs.as_ptr(),
            xs.len(),
            Some(trampoline_unwind::<F>),
            (&raw mut f).cast(),
        );
    }
}

// ---------------------------------------------------------------------------
// Part 4 · send_c_handle
// ---------------------------------------------------------------------------

/// Owns one `ctx *` from the pretend C library and frees it in `Drop`.
///
/// `Send` (by the `unsafe impl` below) but not `Sync`: share it between
/// threads as `Mutex<Handle>`.
///
/// Without `unsafe impl Send`, a handle is not `Send`, because `NonNull` is
/// not (E0277):
///
/// ```compile_fail,E0277
/// use deep_dive::ffi_lab::Ctx;
/// use std::ptr::NonNull;
///
/// struct Handle(NonNull<Ctx>);
///
/// fn assert_send<T: Send>() {}
/// assert_send::<Handle>();
/// ```
///
/// With it, it is (positive control, one line longer):
///
/// ```
/// use deep_dive::ffi_lab::Ctx;
/// use std::ptr::NonNull;
///
/// struct Handle(NonNull<Ctx>);
/// // SAFETY: (see the real `Handle` for the argument)
/// unsafe impl Send for Handle {}
///
/// fn assert_send<T: Send>() {}
/// assert_send::<Handle>();
/// ```
///
/// The real `Handle` is not `Sync` (E0277):
///
/// ```compile_fail,E0277
/// use deep_dive::ffi_lab::Handle;
///
/// fn assert_sync<T: Sync>() {}
/// assert_sync::<Handle>();
/// ```
///
/// but a `Mutex<Handle>` is (positive control):
///
/// ```
/// use deep_dive::ffi_lab::Handle;
/// use std::sync::Mutex;
///
/// fn assert_sync<T: Sync>() {}
/// assert_sync::<Mutex<Handle>>();
/// ```
pub struct Handle(NonNull<Ctx>);

impl Handle {
    /// Creates a context through the C library.
    pub fn new() -> Handle {
        let raw = sys::ffi_lab_ctx_new();
        Handle(NonNull::new(raw).expect("ffi_lab_ctx_new never returns NULL"))
    }

    /// Increments the context's counter and returns the new value.
    pub fn bump(&self) -> i32 {
        // SAFETY: `self.0` is a live context (freed only in `Drop`). `Handle`
        // is not `Sync`, so every `&Handle` stays on one thread, and `bump`
        // does not call back into Rust: no other call on this context can run
        // at the same time.
        unsafe { sys::ffi_lab_ctx_bump(self.0.as_ptr()) }
    }
}

impl Default for Handle {
    fn default() -> Handle {
        Handle::new()
    }
}

impl Drop for Handle {
    fn drop(&mut self) {
        // SAFETY: `self.0` came from `ffi_lab_ctx_new`; `Drop` runs once and
        // nothing can use the handle afterwards, so it is freed exactly once.
        unsafe { sys::ffi_lab_ctx_free(self.0.as_ptr()) };
    }
}

// SAFETY: the library allows a context to be used from any thread, as long as
// calls on it do not overlap: it has no thread-local state and no thread
// affinity. Moving the only `Handle` to another thread moves the right to call
// into the context along with it, and `Drop` may free it on whichever thread
// holds it last. Deliberately NOT `Sync`: a shared `&Handle` on two threads
// could run `bump` on the same context concurrently, a data race in C.
unsafe impl Send for Handle {}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;
    use std::sync::{Barrier, Mutex, MutexGuard, PoisonError};
    use std::thread;

    /// Broken variants, compiled only for the tests so that the crate's public
    /// API stays sound. Each one is exercised by a demonstration below.
    mod broken {
        use super::super::{Handle, strlen, sys};
        use std::ffi::{CString, c_int, c_void};

        /// BROKEN: `as_ptr()` on a temporary. The `CString` is dropped at the
        /// end of the `let` statement, so `p` dangles before `strlen` reads
        /// it: a use-after-free. See `dangling_as_ptr_is_a_use_after_free`.
        // The lint catches exactly this bug; it is allowed here only because
        // this function exists to demonstrate it under Miri.
        #[allow(dangling_pointers_from_temporaries)]
        pub fn c_len_dangling(s: &str) -> usize {
            let p = CString::new(s).unwrap().as_ptr();
            // SAFETY: BROKEN on purpose: claims `p` is a live C string, but
            // the `CString` it points into was freed on the previous line.
            unsafe { strlen(p) }
        }

        /// BROKEN: the trampoline without `catch_unwind`. A panic in `f`
        /// reaches the end of an `extern "C"` function, and the process
        /// aborts. See `panic_through_extern_c_aborts_the_process`.
        unsafe extern "C" fn trampoline_unguarded<F: FnMut(i32)>(user: *mut c_void, x: c_int) {
            // SAFETY: `for_each_unguarded` passes a pointer to its local `F`
            // and does not touch it during the call.
            let f = unsafe { &mut *user.cast::<F>() };
            f(x);
        }

        pub fn for_each_unguarded<F: FnMut(i32)>(xs: &[i32], mut f: F) {
            // SAFETY: as in `for_each_catching`, except that a panic in `f`
            // is not caught (which aborts: defined, but fatal).
            unsafe {
                sys::ffi_lab_for_each(
                    xs.as_ptr(),
                    xs.len(),
                    Some(trampoline_unguarded::<F>),
                    (&raw mut f).cast(),
                );
            }
        }

        /// BROKEN: a handle that claims to be `Sync`. Safe code can now share
        /// it between threads and race inside C. See
        /// `sync_handle_lets_two_threads_race`.
        pub struct SyncHandle(pub Handle);

        impl SyncHandle {
            pub fn bump(&self) -> i32 {
                self.0.bump()
            }
        }

        // SAFETY: BROKEN on purpose: `ffi_lab_ctx_bump` is not thread-safe,
        // so sharing a `&SyncHandle` between threads allows overlapping calls.
        unsafe impl Sync for SyncHandle {}
    }

    // C's `free`, for the allocator-mixing demonstration only.
    unsafe extern "C" {
        fn free(p: *mut c_void);
    }

    fn assert_send<T: Send>() {}
    fn assert_sync<T: Sync>() {}

    /// Counts drops, to prove each value is dropped exactly once.
    struct DropCounter<'a>(&'a Cell<usize>);

    impl Drop for DropCounter<'_> {
        fn drop(&mut self) {
            self.0.set(self.0.get() + 1);
        }
    }

    /// The panic message inside a payload, whether `&str` or `String`.
    fn message(payload: &(dyn Any + Send)) -> &str {
        if let Some(s) = payload.downcast_ref::<&str>() {
            s
        } else if let Some(s) = payload.downcast_ref::<String>() {
            s
        } else {
            "<non-string payload>"
        }
    }

    /// Tests that allocate from the pretend library run one at a time, so
    /// that the process-wide `live_allocations()` counter is theirs alone.
    static LIBRARY_TESTS: Mutex<()> = Mutex::new(());

    fn serialize_library_tests() -> MutexGuard<'static, ()> {
        LIBRARY_TESTS.lock().unwrap_or_else(PoisonError::into_inner)
    }

    // ----- Part 1 · call_libc -----

    #[test]
    fn strlen_counts_bytes_before_the_nul() {
        assert_eq!(c_strlen(c"hello"), 5);
        assert_eq!(c_strlen(c""), 0);
        // Bytes, not characters: "é" is two bytes in UTF-8.
        assert_eq!(c_strlen(c"caf\u{e9}"), 5);
        assert_eq!(c_strlen(c"caf\u{e9}"), c"caf\u{e9}".count_bytes());
    }

    #[test]
    fn hypot_is_a_safe_fn() {
        // No `unsafe` block: the declaration promised there is nothing to
        // uphold.
        assert!((hypot(3.0, 4.0) - 5.0).abs() < 1e-9);
        assert!(hypot(f64::NAN, 1.0).is_nan());
        assert_eq!(hypot(f64::INFINITY, 1.0), f64::INFINITY);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Miri has no shim for C's `abs`")]
    fn checked_abs_refuses_int_min() {
        assert_eq!(checked_abs(-5), Some(5));
        assert_eq!(checked_abs(0), Some(0));
        assert_eq!(checked_abs(i32::MAX), Some(i32::MAX));
        assert_eq!(checked_abs(i32::MIN + 1), Some(i32::MAX));
        assert_eq!(checked_abs(i32::MIN), None);
    }

    #[test]
    #[cfg_attr(miri, ignore = "Miri has no shim for C's `div`")]
    fn checked_div_returns_a_repr_c_struct_by_value() {
        assert_eq!(checked_div(7, 2), Some(DivT { quot: 3, rem: 1 }));
        // C99 truncates toward zero, like Rust's `/` and `%`.
        assert_eq!(checked_div(-7, 2), Some(DivT { quot: -3, rem: -1 }));
        assert_eq!(checked_div(1, 0), None);
        assert_eq!(checked_div(i32::MIN, -1), None);
        for (n, d) in [
            (100, 7),
            (-100, 7),
            (100, -7),
            (i32::MIN, 2),
            (i32::MAX, -1),
        ] {
            let r = checked_div(n, d).unwrap();
            assert_eq!((r.quot, r.rem), (n / d, n % d), "div({n}, {d})");
        }
    }

    #[test]
    #[cfg_attr(miri, ignore = "Miri has no shim for C's `qsort`")]
    fn qsort_sorts_with_a_rust_comparator() {
        // The extremes are there for the `*a - *b` bug: `i32::MIN - 1`
        // overflows, so a subtracting comparator would misplace them.
        let mut xs = [5, -3, i32::MAX, 0, 5, i32::MIN, 1, -1];
        qsort_i32(&mut xs);
        assert_eq!(xs, [i32::MIN, -3, -1, 0, 1, 5, 5, i32::MAX]);

        let mut empty: [i32; 0] = [];
        qsort_i32(&mut empty);
        let mut one = [42];
        qsort_i32(&mut one);
        assert_eq!(one, [42]);
    }

    // ----- Part 2 · cstring_ownership -----

    #[test]
    fn cstring_new_rejects_an_interior_nul() {
        let err = CString::new("a\0b").unwrap_err();
        assert_eq!(err.nul_position(), 1);
        assert_eq!(err.into_vec(), b"a\0b");
        assert_eq!(c_len("a\0b").unwrap_err().nul_position(), 1);
        assert_eq!(c_len("hello"), Ok(5));
    }

    #[test]
    fn to_string_lossy_replaces_invalid_utf8() {
        use std::borrow::Cow;
        // 0xFF never appears in UTF-8.
        let bytes = c"caf\xff";
        assert!(bytes.to_str().is_err());
        let lossy = bytes.to_string_lossy();
        assert_eq!(lossy, "caf\u{FFFD}");
        assert!(matches!(lossy, Cow::Owned(_)));
        // Valid UTF-8 is borrowed, not copied.
        assert!(matches!(c"cafe".to_string_lossy(), Cow::Borrowed("cafe")));
    }

    #[test]
    fn into_raw_and_from_raw_round_trip() {
        let raw: *mut c_char = CString::new("ferris").unwrap().into_raw();
        // Ownership is "in C" now: nothing on the Rust side will free it.
        // SAFETY: `raw` came from `into_raw`, so it is a live NUL-terminated
        // string.
        assert_eq!(unsafe { strlen(raw) }, 6);
        // SAFETY: `raw` came from `CString::into_raw`, its length is
        // unchanged, and it is taken back exactly once.
        let back = unsafe { CString::from_raw(raw) };
        assert_eq!(back.into_string().unwrap(), "ferris");
    }

    #[test]
    fn greeting_is_freed_by_the_library_exactly_once() {
        let _serial = serialize_library_tests();
        let before = live_allocations();
        {
            let s = greeting(c"Ferris").unwrap();
            assert_eq!(s.as_c_str(), c"Hello, Ferris!");
            assert_eq!(c_strlen(s.as_c_str()), "Hello, Ferris!".len());
            assert_eq!(live_allocations(), before + 1);
            // Invalid UTF-8 in the name survives as U+FFFD.
            let odd = greeting(c"caf\xff").unwrap();
            assert_eq!(odd.as_c_str().to_str(), Ok("Hello, caf\u{FFFD}!"));
            assert_eq!(live_allocations(), before + 2);
        }
        assert_eq!(live_allocations(), before);
    }

    #[test]
    fn exported_functions_treat_null_like_c_does() {
        // SAFETY: `ffi_lab_greeting` documents NULL as allowed.
        let greeting = unsafe { sys::ffi_lab_greeting(std::ptr::null()) };
        assert!(greeting.is_null());
        // SAFETY: `ffi_lab_string_free` documents NULL as a no-op.
        unsafe { sys::ffi_lab_string_free(std::ptr::null_mut()) };
    }

    /// Demonstration: `CString::new(..).unwrap().as_ptr()` dangles. Run it
    /// under Miri, which reports "memory access failed: allocN has been
    /// freed, so this pointer is dangling":
    ///
    /// ```text
    /// cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::dangling_as_ptr_is_a_use_after_free
    /// ```
    #[test]
    #[ignore = "undefined behavior on purpose: run under Miri (see the doc comment)"]
    fn dangling_as_ptr_is_a_use_after_free() {
        if !cfg!(miri) {
            eprintln!("skipped natively: this reads freed memory; run it under Miri");
            return;
        }
        broken::c_len_dangling("hello");
    }

    /// Demonstration: C's `free` on a `CString::into_raw` pointer mixes
    /// allocators. Miri reports "deallocating allocN, which is Rust heap
    /// memory, using C heap deallocation operation":
    ///
    /// ```text
    /// cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::c_free_on_a_cstring_mixes_allocators
    /// ```
    #[test]
    #[ignore = "undefined behavior on purpose: run under Miri (see the doc comment)"]
    fn c_free_on_a_cstring_mixes_allocators() {
        if !cfg!(miri) {
            eprintln!("skipped natively: this frees Rust memory with C's free; run it under Miri");
            return;
        }
        let raw = CString::new("ferris").unwrap().into_raw();
        // SAFETY: BROKEN on purpose: `raw` belongs to Rust's allocator and must
        // go back through `CString::from_raw`, not C's `free`.
        unsafe { free(raw.cast()) };
    }

    // ----- Part 3 · callback_trampoline -----

    #[test]
    fn for_each_passes_every_value_to_the_closure() {
        let drops = Cell::new(0);
        let mut seen = Vec::new();
        {
            let guard = DropCounter(&drops);
            let seen = &mut seen;
            for_each(&[3, 1, 4, 1, 5], move |x| {
                let _keep_alive = &guard;
                seen.push(x);
            });
        }
        assert_eq!(seen, [3, 1, 4, 1, 5]);
        // The closure (and the guard it owns) was dropped exactly once, by
        // `for_each_catching`, not per call and not never.
        assert_eq!(drops.get(), 1);
    }

    #[test]
    fn empty_slice_never_calls_the_closure() {
        let mut calls = 0;
        for_each(&[], |_| calls += 1);
        assert_eq!(calls, 0);
    }

    #[test]
    fn panicking_closure_returns_err() {
        let drops = Cell::new(0);
        let mut seen = Vec::new();
        let result = {
            let guard = DropCounter(&drops);
            let seen = &mut seen;
            for_each_catching(&[1, 2, 3, 4], move |x| {
                let _keep_alive = &guard;
                seen.push(x);
                if x == 2 {
                    panic!("closure panicked at {x}");
                }
            })
        };
        let payload = result.unwrap_err();
        assert_eq!(message(&*payload), "closure panicked at 2");
        // Calls after the panic were skipped, and the closure was still
        // dropped exactly once.
        assert_eq!(seen, [1, 2]);
        assert_eq!(drops.get(), 1);
    }

    #[test]
    fn for_each_resumes_the_panic_on_the_rust_side() {
        let result = panic::catch_unwind(|| for_each(&[1, 2], |_| panic!("boom")));
        assert_eq!(message(&*result.unwrap_err()), "boom");
    }

    #[test]
    fn c_unwind_lets_the_panic_through() {
        let drops = Cell::new(0);
        let mut seen = Vec::new();
        let result = panic::catch_unwind(AssertUnwindSafe(|| {
            let guard = DropCounter(&drops);
            let seen = &mut seen;
            for_each_unwind(&[1, 2, 3], move |x| {
                let _keep_alive = &guard;
                seen.push(x);
                if x == 2 {
                    panic!("unwound through C-unwind");
                }
            });
        }));
        assert_eq!(message(&*result.unwrap_err()), "unwound through C-unwind");
        // The unwind stopped the loop in the "C" function and dropped the
        // closure on its way out.
        assert_eq!(seen, [1, 2]);
        assert_eq!(drops.get(), 1);
    }

    const ABORT_CHILD_ENV: &str = "FFI_LAB_ABORT_CHILD";

    /// Runs in a child process only (see the next test): a panic reaches the
    /// end of an `extern "C"` function, and the process aborts. Without the
    /// environment variable it does nothing, so `cargo test -- --ignored`
    /// stays safe to run.
    #[test]
    #[ignore = "aborts the process on purpose; run by panic_through_extern_c_aborts_the_process"]
    fn child_panics_through_extern_c() {
        if std::env::var_os(ABORT_CHILD_ENV).is_none() {
            eprintln!("skipped: set {ABORT_CHILD_ENV}=1 to let this test abort the process");
            return;
        }
        broken::for_each_unguarded(&[1, 2, 3], |x| {
            if x == 2 {
                panic!("callback panicked at {x}");
            }
        });
        unreachable!("the process aborts before for_each_unguarded returns");
    }

    #[test]
    #[cfg_attr(miri, ignore = "Miri cannot spawn processes")]
    fn panic_through_extern_c_aborts_the_process() {
        // Re-run this test binary, filtered to the one ignored test above.
        // Test names omit the crate name: `ffi_lab::tests::...`.
        let (_crate_name, module) = module_path!().split_once("::").unwrap();
        let test_name = format!("{module}::child_panics_through_extern_c");
        let exe = std::env::current_exe().unwrap();
        let output = std::process::Command::new(exe)
            .args(["--ignored", "--exact", &test_name, "--nocapture"])
            .env(ABORT_CHILD_ENV, "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);

        assert!(
            stdout.contains("running 1 test"),
            "the filter matched no test:\n{stdout}"
        );
        assert!(
            !output.status.success(),
            "the child exited normally:\n{stderr}"
        );
        #[cfg(unix)]
        {
            use std::os::unix::process::ExitStatusExt;
            const SIGABRT: i32 = 6; // the same number on Linux and macOS
            assert_eq!(output.status.signal(), Some(SIGABRT), "{stderr}");
        }
        // First the closure's panic, then the abort at the ABI boundary.
        assert!(stderr.contains("callback panicked at 2"), "{stderr}");
        assert!(
            stderr.contains("panic in a function that cannot unwind"),
            "{stderr}"
        );
    }

    // ----- Part 4 · send_c_handle -----

    #[test]
    fn handle_is_send_and_mutex_handle_is_sync() {
        // `Handle` itself is not `Sync`: see the `compile_fail` doctest on it.
        assert_send::<Handle>();
        assert_send::<Mutex<Handle>>();
        assert_sync::<Mutex<Handle>>();
    }

    #[test]
    fn handle_moves_to_another_thread() {
        let _serial = serialize_library_tests();
        let before = live_allocations();
        let handle = Handle::new();
        assert_eq!(handle.bump(), 1);
        let handle = thread::Builder::new()
            .spawn(move || {
                assert_eq!(handle.bump(), 2);
                handle
            })
            .unwrap()
            .join()
            .unwrap();
        assert_eq!(handle.bump(), 3);
        assert_eq!(live_allocations(), before + 1);
        drop(handle);
        assert_eq!(live_allocations(), before);
    }

    #[test]
    fn mutex_shares_one_context_between_threads() {
        const THREADS: usize = 4;
        const BUMPS: usize = if cfg!(miri) { 5 } else { 1_000 };
        let _serial = serialize_library_tests();
        let before = live_allocations();
        let shared = Mutex::new(Handle::new());
        thread::scope(|s| {
            for _ in 0..THREADS {
                thread::Builder::new()
                    .spawn_scoped(s, || {
                        for _ in 0..BUMPS {
                            shared.lock().unwrap().bump();
                        }
                    })
                    .unwrap();
            }
        });
        let handle = shared.into_inner().unwrap();
        // Every bump happened, none was lost to a race.
        assert_eq!(handle.bump(), (THREADS * BUMPS) as i32 + 1);
        drop(handle);
        assert_eq!(live_allocations(), before);
    }

    /// Demonstration: why `Handle` must not be `Sync`. Two threads share a
    /// `&SyncHandle` and bump the same context. Miri reports "Data race
    /// detected between (1) non-atomic write on thread `unnamed-..` and (2)
    /// non-atomic read on thread `unnamed-..`":
    ///
    /// ```text
    /// cargo +nightly miri test --manifest-path deep-dive/Cargo.toml --lib -- --ignored --exact ffi_lab::tests::sync_handle_lets_two_threads_race
    /// ```
    ///
    /// The barrier makes the report independent of the schedule: once both
    /// threads are past it, nothing orders the two bumps, in any execution.
    /// Without it, 3 of 20 Miri seeds reported nothing when this was written:
    /// in those executions some other synchronization happened to order the
    /// two calls. The race was still in the code; Miri only reports the races
    /// of the execution it explores.
    #[test]
    #[ignore = "undefined behavior on purpose: run under Miri (see the doc comment)"]
    fn sync_handle_lets_two_threads_race() {
        if !cfg!(miri) {
            eprintln!("skipped natively: this is a data race; run it under Miri");
            return;
        }
        let _serial = serialize_library_tests();
        let shared = broken::SyncHandle(Handle::new());
        let both_started = Barrier::new(2);
        thread::scope(|s| {
            for _ in 0..2 {
                thread::Builder::new()
                    .spawn_scoped(s, || {
                        both_started.wait();
                        shared.bump()
                    })
                    .unwrap();
            }
        });
    }
}
